CREATE SCHEMA "public";
CREATE TABLE "__EFMigrationsHistory" (
	"MigrationId" varchar(150),
	"ProductVersion" varchar(32) NOT NULL,
	CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY("MigrationId")
);
CREATE TABLE "AiConversations" (
	"Id" serial PRIMARY KEY,
	"UserId" varchar(100) NOT NULL,
	"Title" varchar(255) DEFAULT 'New Conversation' NOT NULL,
	"Summary" text,
	"LastMessageAt" timestamp with time zone,
	"MessageCount" integer DEFAULT 0 NOT NULL,
	"IsArchived" boolean DEFAULT false NOT NULL,
	"IsPinned" boolean DEFAULT false NOT NULL,
	"CreatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	"UpdatedAt" timestamp with time zone,
	"DeletedAt" timestamp with time zone,
	"IsDeleted" boolean DEFAULT false NOT NULL
);
CREATE TABLE "AiMessages" (
	"Id" serial PRIMARY KEY,
	"ConversationId" integer NOT NULL,
	"Role" varchar(20) NOT NULL,
	"Content" text NOT NULL,
	"Feedback" varchar(20),
	"IsRegenerated" boolean DEFAULT false NOT NULL,
	"Metadata" jsonb,
	"CreatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "AiMessages_Feedback_check" CHECK (CHECK ((("Feedback")::text = ANY ((ARRAY['liked'::character varying, 'disliked'::character varying, NULL::character varying])::text[])))),
	CONSTRAINT "AiMessages_Role_check" CHECK (CHECK ((("Role")::text = ANY ((ARRAY['user'::character varying, 'assistant'::character varying, 'system'::character varying])::text[]))))
);
CREATE TABLE "ArticleCategories" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "ArticleCategories_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"Name" varchar(100) NOT NULL,
	"Description" varchar(500),
	"ParentCategoryId" integer,
	"IsActive" boolean DEFAULT true NOT NULL,
	"CreatedDate" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "PK_ArticleCategories" PRIMARY KEY("Id")
);
CREATE TABLE "ArticleNotes" (
	"Id" serial PRIMARY KEY,
	"ArticleId" integer NOT NULL,
	"Note" text NOT NULL,
	"CreatedDate" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"CreatedBy" varchar(100) NOT NULL
);
CREATE TABLE "Articles" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "Articles_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ArticleNumber" varchar(50) NOT NULL,
	"Name" varchar(200) NOT NULL,
	"Description" text,
	"CategoryId" integer,
	"Unit" varchar(20) NOT NULL,
	"PurchasePrice" numeric(18, 2) NOT NULL,
	"SalesPrice" numeric(18, 2) NOT NULL,
	"StockQuantity" numeric(18, 2) NOT NULL,
	"MinStockLevel" numeric(18, 2),
	"LocationId" integer,
	"Supplier" varchar(200),
	"IsActive" boolean DEFAULT true NOT NULL,
	"CreatedDate" timestamp with time zone DEFAULT now() NOT NULL,
	"ModifiedDate" timestamp with time zone,
	"Notes" text,
	"Tags" text,
	"Type" varchar(20) DEFAULT 'material',
	"Duration" integer,
	"CreatedBy" varchar(100),
	"ModifiedBy" varchar(100),
	CONSTRAINT "PK_Articles" PRIMARY KEY("Id")
);
CREATE TABLE "Attachments" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "Attachments_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"DispatchId" integer NOT NULL,
	"FileName" varchar(255) NOT NULL,
	"FilePath" varchar(500) NOT NULL,
	"FileSize" bigint NOT NULL,
	"ContentType" varchar(100) NOT NULL,
	"AttachmentType" varchar(50) NOT NULL,
	"UploadedDate" timestamp with time zone DEFAULT now() NOT NULL,
	"UploadedBy" varchar(100) NOT NULL,
	CONSTRAINT "PK_Attachments" PRIMARY KEY("Id")
);
CREATE TABLE "calendar_events" (
	"Id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	"Title" varchar(200) NOT NULL,
	"Description" text,
	"Start" timestamp NOT NULL,
	"End" timestamp NOT NULL,
	"all_day" boolean DEFAULT false NOT NULL,
	"Type" varchar(50) NOT NULL,
	"Status" varchar(20) DEFAULT 'scheduled' NOT NULL,
	"Priority" varchar(10) DEFAULT 'medium' NOT NULL,
	"Category" varchar(50),
	"Color" varchar(7),
	"Location" text,
	"Attendees" jsonb,
	"related_type" varchar(20),
	"related_id" uuid,
	"contact_id" integer,
	"Reminders" jsonb,
	"Recurring" jsonb,
	"is_private" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"created_by" uuid NOT NULL,
	"modified_by" uuid
);
CREATE TABLE "CalendarEvents" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "CalendarEvents_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"Title" varchar(200) NOT NULL,
	"Description" text,
	"StartDate" timestamp with time zone NOT NULL,
	"EndDate" timestamp with time zone NOT NULL,
	"Location" varchar(200),
	"EventTypeId" integer,
	"IsAllDay" boolean DEFAULT false NOT NULL,
	"RecurrenceRule" varchar(500),
	"CreatedDate" timestamp with time zone DEFAULT now() NOT NULL,
	"CreatedBy" varchar(100) NOT NULL,
	"ModifiedDate" timestamp with time zone,
	"ModifiedBy" varchar(100),
	CONSTRAINT "PK_CalendarEvents" PRIMARY KEY("Id")
);
CREATE TABLE "ContactNotes" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "ContactNotes_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ContactId" integer NOT NULL,
	"Note" text NOT NULL,
	"CreatedDate" timestamp with time zone DEFAULT now() NOT NULL,
	"CreatedBy" varchar(100) NOT NULL,
	CONSTRAINT "PK_ContactNotes" PRIMARY KEY("Id")
);
CREATE TABLE "Contacts" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "Contacts_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"FirstName" varchar(100) NOT NULL,
	"LastName" varchar(100) NOT NULL,
	"Email" varchar(255),
	"Phone" varchar(20),
	"Company" varchar(200),
	"Position" varchar(100),
	"Address" varchar(500),
	"City" varchar(100),
	"Country" varchar(100),
	"PostalCode" varchar(20),
	"Notes" text,
	"IsActive" boolean DEFAULT true NOT NULL,
	"CreatedDate" timestamp with time zone DEFAULT now() NOT NULL,
	"CreatedBy" varchar(100) NOT NULL,
	"ModifiedDate" timestamp with time zone,
	"ModifiedBy" varchar(100),
	"Name" varchar(255) NOT NULL,
	"Status" varchar(50) DEFAULT 'active',
	"Type" varchar(50) DEFAULT 'individual',
	"Avatar" varchar(500),
	"Favorite" boolean DEFAULT false,
	"LastContactDate" timestamp,
	"IsDeleted" boolean DEFAULT false,
	"Cin" varchar(50),
	"MatriculeFiscale" varchar(100),
	"Latitude" numeric(10, 7),
	"Longitude" numeric(10, 7),
	"HasLocation" integer DEFAULT 0,
	CONSTRAINT "PK_Contacts" PRIMARY KEY("Id")
);
CREATE TABLE "ContactTagAssignments" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "ContactTagAssignments_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ContactId" integer NOT NULL,
	"TagId" integer NOT NULL,
	"AssignedDate" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "PK_ContactTagAssignments" PRIMARY KEY("Id")
);
CREATE TABLE "ContactTags" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "ContactTags_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"Name" varchar(50) NOT NULL,
	"Color" varchar(7),
	"CreatedDate" timestamp with time zone DEFAULT now() NOT NULL,
	"CreatedBy" varchar(100) NOT NULL,
	CONSTRAINT "PK_ContactTags" PRIMARY KEY("Id")
);
CREATE TABLE "Currencies" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "Currencies_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"Code" varchar(3) NOT NULL,
	"Name" varchar(100) NOT NULL,
	"Symbol" varchar(10) NOT NULL,
	"IsActive" boolean DEFAULT true NOT NULL,
	"IsDefault" boolean DEFAULT false,
	"SortOrder" integer DEFAULT 0,
	"CreatedUser" varchar(100) DEFAULT 'system',
	"CreatedAt" timestamp DEFAULT now(),
	"IsDeleted" boolean DEFAULT false,
	CONSTRAINT "PK_Currencies" PRIMARY KEY("Id")
);
CREATE TABLE "DailyTasks" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "DailyTasks_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"Title" varchar(200) NOT NULL,
	"Description" text,
	"DueDate" timestamp with time zone NOT NULL,
	"IsCompleted" boolean DEFAULT false NOT NULL,
	"CompletedDate" timestamp with time zone,
	"AssignedUserId" integer,
	"Priority" varchar(20),
	"CreatedDate" timestamp with time zone DEFAULT now() NOT NULL,
	"CreatedBy" varchar(100) NOT NULL,
	"Status" varchar(20) DEFAULT 'todo',
	"EstimatedHours" numeric(18, 2),
	CONSTRAINT "PK_DailyTasks" PRIMARY KEY("Id")
);
CREATE TABLE "Dispatches" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "Dispatches_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"DispatchNumber" varchar(50) NOT NULL,
	"ContactId" integer NOT NULL,
	"ServiceOrderId" integer,
	"ProjectTaskId" integer,
	"ScheduledDate" timestamp with time zone NOT NULL,
	"CompletedDate" timestamp with time zone,
	"Status" text NOT NULL,
	"Priority" varchar(50) NOT NULL,
	"Description" text,
	"SiteAddress" varchar(500) NOT NULL,
	"CreatedDate" timestamp with time zone DEFAULT now() NOT NULL,
	"CreatedBy" varchar(100) NOT NULL,
	"ModifiedDate" timestamp with time zone,
	"ModifiedBy" varchar(100),
	"JobId" varchar(50),
	"DispatchedBy" varchar(50),
	"DispatchedAt" timestamp with time zone,
	"CompletionPercentage" integer DEFAULT 0,
	"RequiredSkills" text[],
	"WorkLocationJson" jsonb,
	"ActualStartTime" timestamp with time zone,
	"ActualEndTime" timestamp with time zone,
	"ActualDuration" integer,
	"IsDeleted" boolean DEFAULT false,
	CONSTRAINT "PK_Dispatches" PRIMARY KEY("Id")
);
CREATE TABLE "DispatchHistory" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "DispatchHistory_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"DispatchId" integer NOT NULL,
	"Status" varchar(20) NOT NULL,
	"StatusDate" timestamp with time zone DEFAULT now() NOT NULL,
	"Notes" text,
	"ChangedBy" varchar(100) NOT NULL,
	CONSTRAINT "PK_DispatchHistory" PRIMARY KEY("Id")
);
CREATE TABLE "DispatchTechnicians" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "DispatchTechnicians_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"DispatchId" integer NOT NULL,
	"TechnicianId" integer NOT NULL,
	"AssignedDate" timestamp with time zone DEFAULT now() NOT NULL,
	"Role" varchar(50),
	CONSTRAINT "PK_DispatchTechnicians" PRIMARY KEY("Id")
);
CREATE TABLE "Documents" (
	"Id" serial PRIMARY KEY,
	"FileName" varchar(255) NOT NULL,
	"OriginalName" varchar(500) NOT NULL,
	"FilePath" varchar(1000) NOT NULL,
	"FileSize" bigint NOT NULL,
	"ContentType" varchar(100) NOT NULL,
	"ModuleType" varchar(50),
	"ModuleId" varchar(100),
	"ModuleName" varchar(255),
	"Category" varchar(50) DEFAULT 'crm' NOT NULL,
	"Description" varchar(1000),
	"Tags" varchar(500),
	"IsPublic" boolean DEFAULT false NOT NULL,
	"UploadedBy" varchar(100) NOT NULL,
	"UploadedByName" varchar(200),
	"UploadedAt" timestamp DEFAULT now() NOT NULL,
	"UpdatedAt" timestamp
);
CREATE TABLE "DynamicFormResponses" (
	"Id" serial PRIMARY KEY,
	"FormId" integer NOT NULL,
	"FormVersion" integer NOT NULL,
	"EntityType" varchar(50),
	"EntityId" varchar(100),
	"Responses" jsonb DEFAULT '{}' NOT NULL,
	"Notes" varchar(2000),
	"SubmittedBy" varchar(100) NOT NULL,
	"SubmittedAt" timestamp with time zone DEFAULT now() NOT NULL,
	"SubmitterName" varchar(200),
	"SubmitterEmail" varchar(200),
	"IsPublicSubmission" boolean DEFAULT false NOT NULL
);
CREATE TABLE "DynamicForms" (
	"Id" serial PRIMARY KEY,
	"NameEn" varchar(200) NOT NULL,
	"NameFr" varchar(200) NOT NULL,
	"DescriptionEn" varchar(1000),
	"DescriptionFr" varchar(1000),
	"Status" integer DEFAULT 0 NOT NULL,
	"Version" integer DEFAULT 1 NOT NULL,
	"Category" varchar(100),
	"Fields" jsonb DEFAULT '[]' NOT NULL,
	"CreatedUser" varchar(100),
	"ModifyUser" varchar(100),
	"CreatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	"UpdatedAt" timestamp with time zone,
	"CreatedBy" varchar(100),
	"ModifiedBy" varchar(100),
	"IsDeleted" boolean DEFAULT false NOT NULL,
	"DeletedAt" timestamp with time zone,
	"DeletedBy" varchar(100),
	"IsActive" boolean DEFAULT true NOT NULL,
	"IsPublic" boolean DEFAULT false NOT NULL,
	"PublicSlug" varchar(200) CONSTRAINT "DynamicForms_PublicSlug_key" UNIQUE,
	"ThankYouSettings" jsonb
);
CREATE TABLE "EntityFormDocuments" (
	"Id" serial PRIMARY KEY,
	"EntityType" varchar(50) NOT NULL,
	"EntityId" integer NOT NULL,
	"FormId" integer NOT NULL,
	"FormVersion" integer DEFAULT 1 NOT NULL,
	"Title" varchar(500),
	"Status" varchar(20) DEFAULT 'Draft' NOT NULL,
	"Responses" jsonb DEFAULT '{}' NOT NULL,
	"CreatedBy" varchar(255) NOT NULL,
	"CreatedByName" varchar(255),
	"CreatedAt" timestamp DEFAULT CURRENT_TIMESTAMP,
	"UpdatedAt" timestamp,
	"ModifiedBy" varchar(255),
	"IsDeleted" boolean DEFAULT false,
	"DeletedAt" timestamp,
	"DeletedBy" varchar(255),
	CONSTRAINT "EntityFormDocuments_EntityType_check" CHECK (CHECK ((("EntityType")::text = ANY ((ARRAY['offer'::character varying, 'sale'::character varying, 'serviceorder'::character varying, 'dispatch'::character varying])::text[])))),
	CONSTRAINT "EntityFormDocuments_Status_check" CHECK (CHECK ((("Status")::text = ANY ((ARRAY['draft'::character varying, 'completed'::character varying])::text[]))))
);
CREATE TABLE "event_attendees" (
	"Id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	"event_id" uuid NOT NULL,
	"user_id" uuid,
	"Email" varchar(200),
	"Name" varchar(100),
	"Status" varchar(20) DEFAULT 'pending' NOT NULL,
	"Response" text,
	"responded_at" timestamp,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE "event_reminders" (
	"Id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	"event_id" uuid NOT NULL,
	"Type" varchar(20) DEFAULT 'email' NOT NULL,
	"minutes_before" integer NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"sent_at" timestamp,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE "event_types" (
	"Id" varchar(50) PRIMARY KEY,
	"Name" varchar(100) NOT NULL,
	"Description" text,
	"Color" varchar(7) DEFAULT '#3B82F6' NOT NULL,
	"is_default" boolean DEFAULT false NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE "EventAttendees" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "EventAttendees_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"EventId" integer NOT NULL,
	"UserId" integer,
	"Email" varchar(255),
	"ResponseStatus" varchar(20) NOT NULL,
	CONSTRAINT "PK_EventAttendees" PRIMARY KEY("Id")
);
CREATE TABLE "EventReminders" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "EventReminders_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"EventId" integer NOT NULL,
	"ReminderMinutes" integer NOT NULL,
	"ReminderType" varchar(20) NOT NULL,
	CONSTRAINT "PK_EventReminders" PRIMARY KEY("Id")
);
CREATE TABLE "EventTypes" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "EventTypes_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"Name" varchar(100) NOT NULL,
	"Color" varchar(7),
	"IsActive" boolean DEFAULT true NOT NULL,
	CONSTRAINT "PK_EventTypes" PRIMARY KEY("Id")
);
CREATE TABLE "Expenses" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "Expenses_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"DispatchId" integer NOT NULL,
	"ExpenseType" varchar(50) NOT NULL,
	"Amount" numeric(18, 2) NOT NULL,
	"Description" varchar(500),
	"ExpenseDate" timestamp with time zone NOT NULL,
	"ReceiptPath" varchar(500),
	"RecordedBy" varchar(100) NOT NULL,
	"CreatedDate" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "PK_Expenses" PRIMARY KEY("Id")
);
CREATE TABLE "InstallationNotes" (
	"Id" serial PRIMARY KEY,
	"InstallationId" integer NOT NULL,
	"Note" varchar(2000) NOT NULL,
	"CreatedDate" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"CreatedBy" varchar(255)
);
CREATE TABLE "Installations" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "Installations_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"InstallationNumber" varchar(50) NOT NULL,
	"ContactId" integer NOT NULL,
	"SiteAddress" varchar(500) NOT NULL,
	"InstallationType" varchar(100) NOT NULL,
	"InstallationDate" timestamp with time zone NOT NULL,
	"Status" varchar(20) NOT NULL,
	"WarrantyExpiry" timestamp with time zone,
	"Notes" text,
	"CreatedDate" timestamp with time zone DEFAULT now() NOT NULL,
	"CreatedBy" varchar(100) NOT NULL,
	"ModifiedDate" timestamp with time zone,
	"ModifiedBy" varchar(100),
	"Name" varchar(200),
	"Model" varchar(200),
	"Manufacturer" varchar(200),
	"Category" varchar(100),
	"Type" varchar(50),
	"WarrantyFrom" timestamp with time zone,
	"SerialNumber" varchar(100),
	CONSTRAINT "PK_Installations" PRIMARY KEY("Id")
);
CREATE TABLE "InventoryTransactions" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "InventoryTransactions_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ArticleId" integer NOT NULL,
	"TransactionType" varchar(20) NOT NULL,
	"Quantity" numeric(18, 2) NOT NULL,
	"TransactionDate" timestamp with time zone DEFAULT now() NOT NULL,
	"Reference" varchar(100),
	"Notes" text,
	"CreatedBy" varchar(100) NOT NULL,
	CONSTRAINT "PK_InventoryTransactions" PRIMARY KEY("Id")
);
CREATE TABLE "Locations" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "Locations_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"Name" varchar(100) NOT NULL,
	"Description" varchar(500),
	"IsActive" boolean DEFAULT true NOT NULL,
	"CreatedDate" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "PK_Locations" PRIMARY KEY("Id")
);
CREATE TABLE "LookupItems" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "LookupItems_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"Category" varchar(50),
	"Value" varchar(100),
	"DisplayOrder" integer,
	"IsActive" boolean DEFAULT true NOT NULL,
	"CreatedDate" timestamp with time zone DEFAULT now() NOT NULL,
	"ModifiedDate" timestamp with time zone,
	"LookupType" varchar(50),
	"Name" varchar(100),
	"Description" varchar(500),
	"Color" varchar(20),
	"SortOrder" integer DEFAULT 0,
	"CreatedUser" varchar(100) DEFAULT 'system',
	"ModifyUser" varchar(100),
	"UpdatedAt" timestamp,
	"IsDeleted" boolean DEFAULT false,
	"CreatedAt" timestamp DEFAULT now(),
	"IsDefault" boolean DEFAULT false NOT NULL,
	CONSTRAINT "PK_LookupItems" PRIMARY KEY("Id")
);
CREATE TABLE "MainAdminUsers" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "MainAdminUsers_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"Username" varchar(100) NOT NULL,
	"Email" varchar(255) NOT NULL,
	"PasswordHash" varchar(500) NOT NULL,
	"FirstName" varchar(100) NOT NULL,
	"LastName" varchar(100) NOT NULL,
	"IsActive" boolean DEFAULT true NOT NULL,
	"CreatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	"LastLoginDate" timestamp with time zone,
	"OnboardingCompleted" boolean DEFAULT false NOT NULL,
	"AccessToken" text,
	"RefreshToken" text,
	"TokenExpiresAt" timestamp,
	"PhoneNumber" varchar(20),
	"Country" varchar(2),
	"Industry" varchar(100) DEFAULT '',
	"CompanyName" varchar(255),
	"CompanyWebsite" varchar(500),
	"PreferencesJson" text,
	"UpdatedAt" timestamp,
	"LastLoginAt" timestamp,
	CONSTRAINT "PK_MainAdminUsers" PRIMARY KEY("Id")
);
CREATE TABLE "MaintenanceHistory" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "MaintenanceHistory_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"InstallationId" integer NOT NULL,
	"MaintenanceDate" timestamp with time zone NOT NULL,
	"MaintenanceType" varchar(50) NOT NULL,
	"Description" text,
	"PerformedBy" varchar(100) NOT NULL,
	"Cost" numeric(18, 2),
	"NextMaintenanceDate" timestamp with time zone,
	"CreatedDate" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "PK_MaintenanceHistory" PRIMARY KEY("Id")
);
CREATE TABLE "MaterialUsage" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "MaterialUsage_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"DispatchId" integer NOT NULL,
	"ArticleId" integer,
	"Description" varchar(500) NOT NULL,
	"Quantity" numeric(18, 2) NOT NULL,
	"UnitPrice" numeric(18, 2) NOT NULL,
	"TotalPrice" numeric(18, 2) NOT NULL,
	"UsedDate" timestamp with time zone DEFAULT now() NOT NULL,
	"RecordedBy" varchar(100) NOT NULL,
	CONSTRAINT "PK_MaterialUsage" PRIMARY KEY("Id")
);
CREATE TABLE "Notes" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "Notes_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"DispatchId" integer NOT NULL,
	"NoteText" text NOT NULL,
	"NoteType" varchar(50) NOT NULL,
	"IsInternal" boolean DEFAULT false NOT NULL,
	"CreatedDate" timestamp with time zone DEFAULT now() NOT NULL,
	"CreatedBy" varchar(100) NOT NULL,
	CONSTRAINT "PK_Notes" PRIMARY KEY("Id")
);
CREATE TABLE "Notifications" (
	"Id" serial PRIMARY KEY,
	"UserId" integer NOT NULL,
	"Title" varchar(100) NOT NULL,
	"Description" varchar(500) NOT NULL,
	"Type" varchar(50) DEFAULT 'info' NOT NULL,
	"Category" varchar(50) DEFAULT 'system' NOT NULL,
	"Link" varchar(255),
	"RelatedEntityId" integer,
	"RelatedEntityType" varchar(50),
	"IsRead" boolean DEFAULT false NOT NULL,
	"ReadAt" timestamp,
	"CreatedAt" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE "offer_activities" (
	"id" varchar(50) PRIMARY KEY,
	"offer_id" varchar(50) NOT NULL,
	"type" varchar(50) NOT NULL,
	"description" varchar(500) NOT NULL,
	"details" text,
	"old_value" varchar(255),
	"new_value" varchar(255),
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"created_by" varchar(50) NOT NULL,
	"created_by_name" varchar(255) NOT NULL
);
CREATE TABLE "offer_items" (
	"id" varchar(50) PRIMARY KEY,
	"offer_id" varchar(50) NOT NULL,
	"type" varchar(20) NOT NULL,
	"article_id" varchar(50) NOT NULL,
	"item_name" varchar(255) NOT NULL,
	"item_code" varchar(100),
	"description" text,
	"quantity" numeric(10, 2) DEFAULT '1' NOT NULL,
	"unit_price" numeric(15, 2) DEFAULT '0' NOT NULL,
	"total_price" numeric(15, 2) GENERATED ALWAYS AS (((quantity * unit_price) * ((1)::numeric - (COALESCE(discount, (0)::numeric) / (100)::numeric)))) STORED,
	"discount" numeric(15, 2) DEFAULT '0',
	"discount_type" varchar(20) DEFAULT 'percentage',
	"installation_id" varchar(50),
	"installation_name" varchar(255)
);
CREATE TABLE "OfferActivities" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "OfferActivities_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"OfferId" integer NOT NULL,
	"ActivityType" varchar(50) NOT NULL,
	"Description" text,
	"ActivityDate" timestamp with time zone DEFAULT now() NOT NULL,
	"PerformedBy" varchar(100) NOT NULL,
	CONSTRAINT "PK_OfferActivities" PRIMARY KEY("Id")
);
CREATE TABLE "OfferItems" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "OfferItems_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"OfferId" integer NOT NULL,
	"ArticleId" integer,
	"Description" varchar(500) NOT NULL,
	"Quantity" numeric(18, 2) NOT NULL,
	"UnitPrice" numeric(18, 2) NOT NULL,
	"Discount" numeric(5, 2),
	"TaxRate" numeric(5, 2) NOT NULL,
	"LineTotal" numeric(18, 2) NOT NULL,
	"DisplayOrder" integer NOT NULL,
	"Type" varchar(20) DEFAULT 'article',
	"ItemName" varchar(255),
	"ItemCode" varchar(100),
	"InstallationId" varchar(50),
	"InstallationName" varchar(255),
	"DiscountType" varchar(20) DEFAULT 'percentage',
	CONSTRAINT "PK_OfferItems" PRIMARY KEY("Id")
);
CREATE TABLE "Offers" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "Offers_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"OfferNumber" varchar(50) NOT NULL,
	"ContactId" integer NOT NULL,
	"OfferDate" timestamp with time zone NOT NULL,
	"ValidUntil" timestamp with time zone,
	"Status" text NOT NULL,
	"TotalAmount" numeric(18, 2) NOT NULL,
	"DiscountPercent" numeric(5, 2),
	"DiscountAmount" numeric(18, 2),
	"TaxAmount" numeric(18, 2) NOT NULL,
	"GrandTotal" numeric(18, 2) NOT NULL,
	"Notes" text,
	"TermsAndConditions" text,
	"CreatedDate" timestamp with time zone DEFAULT now() NOT NULL,
	"CreatedBy" varchar(100) NOT NULL,
	"ModifiedDate" timestamp with time zone,
	"ModifiedBy" varchar(100),
	"Title" varchar(255),
	"Description" text,
	"Currency" varchar(3) DEFAULT 'TND',
	"Taxes" numeric(18, 2) DEFAULT '0',
	"Discount" numeric(18, 2) DEFAULT '0',
	"Category" varchar(50),
	"Source" varchar(50),
	"BillingAddress" text,
	"BillingPostalCode" varchar(20),
	"BillingCountry" varchar(100),
	"DeliveryAddress" text,
	"DeliveryPostalCode" varchar(20),
	"DeliveryCountry" varchar(100),
	"AssignedTo" varchar(50),
	"AssignedToName" varchar(255),
	"Tags" text[],
	"UpdatedAt" timestamp with time zone DEFAULT now(),
	"LastActivity" timestamp with time zone,
	"ConvertedToSaleId" varchar(50),
	"ConvertedToServiceOrderId" varchar(50),
	"ConvertedAt" timestamp with time zone,
	"TaxType" varchar(20) DEFAULT 'percentage',
	"FiscalStamp" numeric(10, 3) DEFAULT '1.000',
	"ContactLatitude" numeric(10, 7),
	"ContactLongitude" numeric(10, 7),
	"ContactHasLocation" integer DEFAULT 0,
	"CreatedByName" varchar(255),
	"DiscountType" varchar(20) DEFAULT 'fixed',
	CONSTRAINT "PK_Offers" PRIMARY KEY("Id")
);
CREATE TABLE "offers" (
	"id" varchar(50) PRIMARY KEY,
	"title" varchar(255) NOT NULL,
	"description" text,
	"contact_id" integer NOT NULL,
	"amount" numeric(15, 2) DEFAULT '0' NOT NULL,
	"currency" varchar(3) DEFAULT 'TND' NOT NULL,
	"taxes" numeric(15, 2) DEFAULT '0',
	"discount" numeric(15, 2) DEFAULT '0',
	"total_amount" numeric(15, 2) GENERATED ALWAYS AS (((amount + COALESCE(taxes, (0)::numeric)) - COALESCE(discount, (0)::numeric))) STORED,
	"status" varchar(20) DEFAULT 'draft' NOT NULL,
	"category" varchar(50),
	"source" varchar(50),
	"billing_address" text,
	"billing_postal_code" varchar(20),
	"billing_country" varchar(100),
	"delivery_address" text,
	"delivery_postal_code" varchar(20),
	"delivery_country" varchar(100),
	"valid_until" timestamp,
	"assigned_to" varchar(50),
	"assigned_to_name" varchar(255),
	"tags" text[],
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"created_by" varchar(50) NOT NULL,
	"last_activity" timestamp,
	"converted_to_sale_id" varchar(50),
	"converted_to_service_order_id" varchar(50),
	"converted_at" timestamp,
	"tax_type" varchar(20) DEFAULT 'percentage',
	"fiscal_stamp" numeric(10, 3) DEFAULT '1.000'
);
CREATE TABLE "PdfSettings" (
	"Id" serial PRIMARY KEY,
	"Module" varchar(50) NOT NULL CONSTRAINT "PdfSettings_Module_key" UNIQUE,
	"SettingsJson" jsonb DEFAULT '{}' NOT NULL,
	"CreatedAt" timestamp DEFAULT now(),
	"UpdatedAt" timestamp DEFAULT now()
);
CREATE TABLE "ProjectColumns" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "ProjectColumns_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ProjectId" integer NOT NULL,
	"Name" varchar(100) NOT NULL,
	"DisplayOrder" integer NOT NULL,
	"Color" varchar(7),
	CONSTRAINT "PK_ProjectColumns" PRIMARY KEY("Id")
);
CREATE TABLE "Projects" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "Projects_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"Name" varchar(200) NOT NULL,
	"Description" text,
	"StartDate" timestamp with time zone,
	"EndDate" timestamp with time zone,
	"Status" varchar(20) NOT NULL,
	"Priority" varchar(20),
	"ContactId" integer,
	"CreatedDate" timestamp with time zone DEFAULT now() NOT NULL,
	"CreatedBy" varchar(100) NOT NULL,
	"ModifiedDate" timestamp with time zone,
	"ModifiedBy" varchar(100),
	"TeamMembers" varchar(1000),
	CONSTRAINT "PK_Projects" PRIMARY KEY("Id")
);
CREATE TABLE "ProjectTasks" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "ProjectTasks_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ProjectId" integer NOT NULL,
	"ColumnId" integer NOT NULL,
	"Title" varchar(200) NOT NULL,
	"Description" text,
	"Priority" varchar(20),
	"DueDate" timestamp with time zone,
	"AssignedUserId" integer,
	"DisplayOrder" integer NOT NULL,
	"CreatedDate" timestamp with time zone DEFAULT now() NOT NULL,
	"CreatedBy" varchar(100) NOT NULL,
	"ModifiedDate" timestamp with time zone,
	"ModifiedBy" varchar(100),
	"EstimatedHours" numeric(18, 2),
	CONSTRAINT "PK_ProjectTasks" PRIMARY KEY("Id")
);
CREATE TABLE "RecurringTaskLogs" (
	"Id" serial PRIMARY KEY,
	"RecurringTaskId" integer NOT NULL,
	"GeneratedProjectTaskId" integer,
	"GeneratedDailyTaskId" integer,
	"GeneratedDate" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"ScheduledFor" timestamp with time zone NOT NULL,
	"Status" varchar(20) DEFAULT 'created' NOT NULL,
	"Notes" varchar(500),
	CONSTRAINT "CK_RecurringTaskLogs_Status" CHECK (CHECK ((("Status")::text = ANY ((ARRAY['created'::character varying, 'skipped'::character varying, 'failed'::character varying])::text[]))))
);
CREATE TABLE "RecurringTasks" (
	"Id" serial PRIMARY KEY,
	"ProjectTaskId" integer,
	"DailyTaskId" integer,
	"RecurrenceType" varchar(50) DEFAULT 'daily' NOT NULL,
	"DaysOfWeek" varchar(50),
	"DayOfMonth" integer,
	"MonthOfYear" integer,
	"Interval" integer DEFAULT 1 NOT NULL,
	"StartDate" timestamp with time zone NOT NULL,
	"EndDate" timestamp with time zone,
	"MaxOccurrences" integer,
	"OccurrenceCount" integer DEFAULT 0 NOT NULL,
	"NextOccurrence" timestamp with time zone,
	"LastGeneratedDate" timestamp with time zone,
	"IsActive" boolean DEFAULT true NOT NULL,
	"IsPaused" boolean DEFAULT false NOT NULL,
	"CreatedDate" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"CreatedBy" varchar(100) NOT NULL,
	"ModifiedDate" timestamp with time zone,
	"ModifiedBy" varchar(100),
	CONSTRAINT "CK_RecurringTasks_RecurrenceType" CHECK (CHECK ((("RecurrenceType")::text = ANY ((ARRAY['daily'::character varying, 'weekly'::character varying, 'monthly'::character varying, 'yearly'::character varying, 'custom'::character varying])::text[]))))
);
CREATE TABLE "RolePermissions" (
	"Id" serial PRIMARY KEY,
	"RoleId" integer NOT NULL UNIQUE,
	"Module" varchar(50) NOT NULL UNIQUE,
	"Action" varchar(50) NOT NULL UNIQUE,
	"Granted" boolean DEFAULT false NOT NULL,
	"CreatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	"UpdatedAt" timestamp with time zone,
	"CreatedBy" varchar(100) DEFAULT 'system',
	"ModifiedBy" varchar(100),
	CONSTRAINT "UQ_RolePermissions_Role_Module_Action" UNIQUE("RoleId","Module","Action")
);
CREATE TABLE "Roles" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "Roles_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"Name" varchar(100) NOT NULL,
	"Description" varchar(500),
	"IsActive" boolean DEFAULT true NOT NULL,
	"CreatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	"CreatedBy" varchar(100) NOT NULL,
	"ModifiedDate" timestamp with time zone,
	"ModifiedBy" varchar(100),
	"UpdatedAt" timestamp,
	"CreatedUser" varchar(100) DEFAULT 'system',
	"ModifyUser" varchar(100),
	"IsDeleted" boolean DEFAULT false NOT NULL,
	CONSTRAINT "PK_Roles" PRIMARY KEY("Id")
);
CREATE TABLE "RoleSkills" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "RoleSkills_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"RoleId" integer NOT NULL,
	"SkillId" integer NOT NULL,
	"RequiredProficiencyLevel" varchar(20),
	"IsRequired" boolean DEFAULT false NOT NULL,
	"AssignedBy" varchar(100) NOT NULL,
	"AssignedAt" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "PK_RoleSkills" PRIMARY KEY("Id")
);
CREATE TABLE "sale_activities" (
	"id" varchar(50) PRIMARY KEY,
	"sale_id" varchar(50) NOT NULL,
	"type" varchar(50) NOT NULL,
	"description" varchar(500) NOT NULL,
	"details" text,
	"old_value" text,
	"new_value" text,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"created_by" varchar(50) NOT NULL,
	"created_by_name" varchar(255) NOT NULL
);
CREATE TABLE "sale_items" (
	"id" varchar(50) PRIMARY KEY,
	"sale_id" varchar(50) NOT NULL,
	"type" varchar(20) NOT NULL,
	"article_id" varchar(50) NOT NULL,
	"item_name" varchar(255) NOT NULL,
	"item_code" varchar(100),
	"description" text,
	"quantity" numeric(10, 2) DEFAULT '1' NOT NULL,
	"unit_price" numeric(15, 2) DEFAULT '0' NOT NULL,
	"total_price" numeric(15, 2) GENERATED ALWAYS AS (((quantity * unit_price) * ((1)::numeric - (COALESCE(discount, (0)::numeric) / (100)::numeric)))) STORED,
	"discount" numeric(15, 2) DEFAULT '0',
	"discount_type" varchar(20) DEFAULT 'percentage',
	"installation_id" varchar(50),
	"installation_name" varchar(255)
);
CREATE TABLE "SaleActivities" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "SaleActivities_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"SaleId" integer NOT NULL,
	"ActivityType" varchar(50) NOT NULL,
	"Description" text,
	"ActivityDate" timestamp with time zone DEFAULT now() NOT NULL,
	"PerformedBy" varchar(100) NOT NULL,
	CONSTRAINT "PK_SaleActivities" PRIMARY KEY("Id")
);
CREATE TABLE "SaleItems" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "SaleItems_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"SaleId" integer NOT NULL,
	"ArticleId" integer,
	"Description" varchar(500) NOT NULL,
	"Quantity" numeric(18, 2) NOT NULL,
	"UnitPrice" numeric(18, 2) NOT NULL,
	"Discount" numeric(5, 2),
	"TaxRate" numeric(5, 2) NOT NULL,
	"LineTotal" numeric(18, 2) NOT NULL,
	"DisplayOrder" integer NOT NULL,
	"Type" varchar(20) DEFAULT 'article',
	"ItemName" varchar(255),
	"ItemCode" varchar(100),
	"InstallationId" varchar(50),
	"InstallationName" varchar(255),
	"DiscountType" varchar(20) DEFAULT 'percentage',
	"RequiresServiceOrder" boolean DEFAULT false,
	"ServiceOrderGenerated" boolean DEFAULT false,
	"ServiceOrderId" varchar(50),
	"FulfillmentStatus" varchar(20) DEFAULT 'pending',
	CONSTRAINT "PK_SaleItems" PRIMARY KEY("Id")
);
CREATE TABLE "sales" (
	"id" varchar(50) PRIMARY KEY,
	"title" varchar(255) NOT NULL,
	"description" text,
	"contact_id" integer NOT NULL,
	"offer_id" varchar(50),
	"amount" numeric(15, 2) DEFAULT '0' NOT NULL,
	"currency" varchar(3) DEFAULT 'TND' NOT NULL,
	"taxes" numeric(15, 2) DEFAULT '0',
	"discount" numeric(15, 2) DEFAULT '0',
	"total_amount" numeric(15, 2) GENERATED ALWAYS AS (((amount + COALESCE(taxes, (0)::numeric)) - COALESCE(discount, (0)::numeric))) STORED,
	"status" varchar(20) DEFAULT 'new_offer' NOT NULL,
	"stage" varchar(20) DEFAULT 'offer' NOT NULL,
	"priority" varchar(20) DEFAULT 'medium' NOT NULL,
	"billing_address" text,
	"billing_postal_code" varchar(20),
	"billing_country" varchar(100),
	"delivery_address" text,
	"delivery_postal_code" varchar(20),
	"delivery_country" varchar(100),
	"estimated_close_date" timestamp,
	"actual_close_date" timestamp,
	"valid_until" timestamp,
	"assigned_to" varchar(50),
	"assigned_to_name" varchar(255),
	"tags" text[],
	"lost_reason" text,
	"materials_fulfillment" varchar(20),
	"service_orders_status" varchar(20),
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"created_by" varchar(50) NOT NULL,
	"last_activity" timestamp,
	"fiscal_stamp" numeric(10, 3) DEFAULT '1.000'
);
CREATE TABLE "Sales" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "Sales_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"SaleNumber" varchar(50) NOT NULL,
	"ContactId" integer NOT NULL,
	"SaleDate" timestamp with time zone NOT NULL,
	"Status" text NOT NULL,
	"TotalAmount" numeric(18, 2) NOT NULL,
	"DiscountPercent" numeric(5, 2),
	"DiscountAmount" numeric(18, 2),
	"TaxAmount" numeric(18, 2) NOT NULL,
	"GrandTotal" numeric(18, 2) NOT NULL,
	"PaymentStatus" varchar(20) NOT NULL,
	"PaymentMethod" varchar(50),
	"Notes" text,
	"CreatedDate" timestamp with time zone DEFAULT now() NOT NULL,
	"CreatedBy" varchar(100) NOT NULL,
	"ModifiedDate" timestamp with time zone,
	"ModifiedBy" varchar(100),
	"Title" varchar(255),
	"Description" text,
	"Currency" varchar(3) DEFAULT 'TND',
	"Taxes" numeric(18, 2) DEFAULT '0',
	"Discount" numeric(18, 2) DEFAULT '0',
	"Stage" varchar(50) DEFAULT 'closed',
	"Priority" varchar(20) DEFAULT 'medium',
	"Category" varchar(50),
	"Source" varchar(50),
	"BillingAddress" text,
	"BillingPostalCode" varchar(20),
	"BillingCountry" varchar(100),
	"DeliveryAddress" text,
	"DeliveryPostalCode" varchar(20),
	"DeliveryCountry" varchar(100),
	"AssignedTo" varchar(50),
	"AssignedToName" varchar(255),
	"Tags" text[],
	"EstimatedCloseDate" timestamp with time zone,
	"ActualCloseDate" timestamp with time zone,
	"ValidUntil" timestamp with time zone,
	"UpdatedAt" timestamp with time zone DEFAULT now(),
	"LastActivity" timestamp with time zone,
	"OfferId" varchar(50),
	"ConvertedFromOfferAt" timestamp with time zone,
	"LostReason" text,
	"MaterialsFulfillment" varchar(20) DEFAULT 'pending',
	"ServiceOrdersStatus" varchar(20) DEFAULT 'pending',
	"CreatedByName" varchar(255),
	"TaxType" varchar(20) DEFAULT 'percentage',
	"FiscalStamp" numeric(10, 3) DEFAULT '1.000',
	"ContactLatitude" numeric(10, 7),
	"ContactLongitude" numeric(10, 7),
	"ContactHasLocation" integer DEFAULT 0,
	"DiscountType" varchar(20) DEFAULT 'fixed',
	CONSTRAINT "PK_Sales" PRIMARY KEY("Id")
);
CREATE TABLE "ServiceOrderExpenses" (
	"Id" serial PRIMARY KEY,
	"ServiceOrderId" integer NOT NULL,
	"TechnicianId" varchar(100),
	"Type" varchar(50) DEFAULT 'other' NOT NULL,
	"Amount" numeric(18, 2) DEFAULT '0' NOT NULL,
	"Currency" varchar(10) DEFAULT 'TND' NOT NULL,
	"Description" text,
	"Date" timestamp with time zone DEFAULT now() NOT NULL,
	"Status" varchar(50) DEFAULT 'pending' NOT NULL,
	"CreatedBy" varchar(100) NOT NULL,
	"CreatedAt" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE "ServiceOrderJobs" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "ServiceOrderJobs_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ServiceOrderId" integer NOT NULL,
	"JobDescription" text NOT NULL,
	"AssignedTechnicianId" integer,
	"Status" varchar(20) NOT NULL,
	"EstimatedHours" numeric(5, 2),
	"ActualHours" numeric(5, 2),
	"CompletedDate" timestamp with time zone,
	"Title" varchar(255),
	"Description" text,
	"SaleItemId" varchar(50),
	"InstallationId" varchar(50),
	"InstallationName" varchar(255),
	"WorkType" varchar(50),
	"Priority" varchar(20) DEFAULT 'medium',
	"ScheduledDate" timestamp with time zone,
	"EstimatedDuration" integer,
	"EstimatedCost" numeric(18, 2),
	"ActualDuration" integer,
	"ActualCost" numeric(18, 2),
	"CompletionPercentage" integer DEFAULT 0,
	"AssignedTechnicianIds" text[],
	"RequiredSkills" text[],
	"Notes" text,
	"UpdatedAt" timestamp with time zone DEFAULT now(),
	CONSTRAINT "PK_ServiceOrderJobs" PRIMARY KEY("Id")
);
CREATE TABLE "ServiceOrderMaterials" (
	"Id" serial PRIMARY KEY,
	"ServiceOrderId" integer NOT NULL,
	"SaleItemId" integer,
	"ArticleId" integer,
	"Name" varchar(255) NOT NULL,
	"Sku" varchar(100),
	"Description" varchar(500),
	"Quantity" numeric(18, 2) DEFAULT '1' NOT NULL,
	"UnitPrice" numeric(18, 2) DEFAULT '0' NOT NULL,
	"TotalPrice" numeric(18, 2) DEFAULT '0' NOT NULL,
	"Status" varchar(50) DEFAULT 'pending' NOT NULL,
	"Source" varchar(50) DEFAULT 'manual' NOT NULL,
	"CreatedBy" varchar(100) NOT NULL,
	"CreatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	"UpdatedAt" timestamp with time zone,
	"InternalComment" varchar(1000),
	"ExternalComment" varchar(1000),
	"Replacing" boolean DEFAULT false NOT NULL,
	"OldArticleModel" varchar(255),
	"OldArticleStatus" varchar(50),
	"InstallationId" varchar(50),
	"InstallationName" varchar(255)
);
CREATE TABLE "ServiceOrderNotes" (
	"Id" serial PRIMARY KEY,
	"ServiceOrderId" integer NOT NULL,
	"Content" text NOT NULL,
	"Type" varchar(20) DEFAULT 'internal' NOT NULL,
	"CreatedBy" varchar(100) NOT NULL,
	"CreatedByName" varchar(255),
	"CreatedAt" timestamp with time zone DEFAULT (now() AT TIME ZONE 'UTC'::text) NOT NULL
);
CREATE TABLE "ServiceOrders" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "ServiceOrders_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"OrderNumber" varchar(50) NOT NULL,
	"ContactId" integer NOT NULL,
	"OrderDate" timestamp with time zone NOT NULL,
	"ServiceType" varchar(100) NOT NULL,
	"Priority" varchar(20) NOT NULL,
	"Status" text NOT NULL,
	"ScheduledDate" timestamp with time zone,
	"CompletedDate" timestamp with time zone,
	"TotalAmount" numeric(18, 2),
	"Notes" text,
	"CreatedDate" timestamp with time zone DEFAULT now() NOT NULL,
	"CreatedBy" varchar(100) NOT NULL,
	"ModifiedDate" timestamp with time zone,
	"ModifiedBy" varchar(100),
	"SaleId" varchar(50),
	"OfferId" varchar(50),
	"Description" text,
	"StartDate" timestamp with time zone,
	"TargetCompletionDate" timestamp with time zone,
	"ActualStartDate" timestamp with time zone,
	"ActualCompletionDate" timestamp with time zone,
	"EstimatedDuration" integer,
	"ActualDuration" integer,
	"EstimatedCost" numeric(18, 2),
	"ActualCost" numeric(18, 2),
	"Discount" numeric(18, 2),
	"DiscountPercentage" numeric(5, 2),
	"Tax" numeric(18, 2),
	"PaymentStatus" varchar(20) DEFAULT 'pending',
	"PaymentTerms" varchar(50),
	"InvoiceNumber" varchar(50),
	"InvoiceDate" timestamp with time zone,
	"CompletionPercentage" integer DEFAULT 0,
	"RequiresApproval" boolean DEFAULT false,
	"ApprovedBy" varchar(50),
	"ApprovalDate" timestamp with time zone,
	"CancellationReason" text,
	"CancellationNotes" text,
	"Tags" text[],
	"CustomFields" jsonb,
	"UpdatedBy" varchar(50),
	"UpdatedAt" timestamp with time zone DEFAULT now(),
	"ContactLatitude" numeric(10, 7),
	"ContactLongitude" numeric(10, 7),
	"ContactHasLocation" integer DEFAULT 0,
	"TechnicallyCompletedAt" timestamp,
	"ServiceCount" integer DEFAULT 0,
	"CompletedDispatchCount" integer DEFAULT 0,
	CONSTRAINT "PK_ServiceOrders" PRIMARY KEY("Id")
);
CREATE TABLE "ServiceOrderTimeEntries" (
	"Id" serial PRIMARY KEY,
	"ServiceOrderId" integer NOT NULL,
	"TechnicianId" varchar(100),
	"WorkType" varchar(50) DEFAULT 'work' NOT NULL,
	"StartTime" timestamp with time zone NOT NULL,
	"EndTime" timestamp with time zone,
	"Duration" integer DEFAULT 0 NOT NULL,
	"Description" text,
	"Billable" boolean DEFAULT true NOT NULL,
	"HourlyRate" numeric(18, 2),
	"TotalCost" numeric(18, 2),
	"Status" varchar(50) DEFAULT 'pending' NOT NULL,
	"CreatedBy" varchar(100) NOT NULL,
	"CreatedAt" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE "Skills" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "Skills_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"Name" varchar(100) NOT NULL,
	"Category" varchar(50),
	"Description" varchar(500),
	"IsActive" boolean DEFAULT true NOT NULL,
	"CreatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	"CreatedBy" varchar(100) NOT NULL,
	"Level" varchar(20),
	"UpdatedAt" timestamp,
	"CreatedUser" varchar(100) DEFAULT 'system',
	"ModifyUser" varchar(100),
	"IsDeleted" boolean DEFAULT false NOT NULL,
	CONSTRAINT "PK_Skills" PRIMARY KEY("Id")
);
CREATE TABLE "stock_transactions" (
	"id" serial PRIMARY KEY,
	"article_id" integer NOT NULL,
	"transaction_type" varchar(50) NOT NULL,
	"quantity" numeric(18, 2) NOT NULL,
	"previous_stock" numeric(18, 2) NOT NULL,
	"new_stock" numeric(18, 2) NOT NULL,
	"reason" varchar(255),
	"reference_type" varchar(50),
	"reference_id" varchar(50),
	"reference_number" varchar(100),
	"notes" text,
	"performed_by" varchar(100) NOT NULL,
	"performed_by_name" varchar(200),
	"ip_address" varchar(45),
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE "SystemLogs" (
	"Id" serial PRIMARY KEY,
	"Timestamp" timestamp with time zone DEFAULT now() NOT NULL,
	"Level" varchar(20) NOT NULL,
	"Message" text NOT NULL,
	"Module" varchar(100) NOT NULL,
	"Action" varchar(50) DEFAULT 'other' NOT NULL,
	"UserId" varchar(100),
	"UserName" varchar(200),
	"EntityType" varchar(100),
	"EntityId" varchar(100),
	"Details" text,
	"IpAddress" varchar(45),
	"UserAgent" text,
	"Metadata" jsonb,
	CONSTRAINT "SystemLogs_Action_check" CHECK (CHECK ((("Action")::text = ANY (ARRAY['create'::text, 'read'::text, 'update'::text, 'delete'::text, 'login'::text, 'logout'::text, 'export'::text, 'import'::text, 'other'::text])))),
	CONSTRAINT "SystemLogs_Level_check" CHECK (CHECK ((("Level")::text = ANY (ARRAY['info'::text, 'warning'::text, 'error'::text, 'success'::text]))))
);
CREATE TABLE "TaskAttachments" (
	"Id" serial PRIMARY KEY,
	"ProjectTaskId" integer,
	"DailyTaskId" integer,
	"FileName" varchar(255) NOT NULL,
	"OriginalFileName" varchar(255) NOT NULL,
	"FileUrl" varchar(500) NOT NULL,
	"MimeType" varchar(100),
	"FileSize" bigint NOT NULL,
	"UploadedBy" integer NOT NULL,
	"UploadedByName" varchar(255) NOT NULL,
	"UploadedAt" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"Caption" varchar(500),
	"IsDeleted" boolean DEFAULT false NOT NULL
);
CREATE TABLE "TaskChecklistItems" (
	"Id" serial PRIMARY KEY,
	"ChecklistId" integer NOT NULL,
	"Title" varchar(500) NOT NULL,
	"IsCompleted" boolean DEFAULT false NOT NULL,
	"CompletedAt" timestamp with time zone,
	"CompletedById" integer,
	"CompletedByName" varchar(100),
	"SortOrder" integer DEFAULT 0 NOT NULL,
	"CreatedDate" timestamp with time zone DEFAULT now() NOT NULL,
	"CreatedBy" varchar(100) NOT NULL,
	"ModifiedDate" timestamp with time zone,
	"ModifiedBy" varchar(100)
);
CREATE TABLE "TaskChecklists" (
	"Id" serial PRIMARY KEY,
	"ProjectTaskId" integer,
	"DailyTaskId" integer,
	"Title" varchar(255) NOT NULL,
	"Description" text,
	"IsExpanded" boolean DEFAULT true NOT NULL,
	"SortOrder" integer DEFAULT 0 NOT NULL,
	"CreatedDate" timestamp with time zone DEFAULT now() NOT NULL,
	"CreatedBy" varchar(100) NOT NULL,
	"ModifiedDate" timestamp with time zone,
	"ModifiedBy" varchar(100)
);
CREATE TABLE "TaskComments" (
	"Id" serial PRIMARY KEY,
	"TaskId" integer NOT NULL,
	"Comment" text NOT NULL,
	"CreatedBy" varchar(255) NOT NULL,
	"CreatedDate" timestamp DEFAULT now()
);
CREATE TABLE "TaskTimeEntries" (
	"Id" serial PRIMARY KEY,
	"ProjectTaskId" integer,
	"DailyTaskId" integer,
	"UserId" integer NOT NULL,
	"UserName" varchar(100),
	"StartTime" timestamp with time zone NOT NULL,
	"EndTime" timestamp with time zone,
	"Duration" numeric(18, 2) DEFAULT '0' NOT NULL,
	"Description" text,
	"IsBillable" boolean DEFAULT true NOT NULL,
	"HourlyRate" numeric(18, 2),
	"TotalCost" numeric(18, 2),
	"WorkType" varchar(50) DEFAULT 'work' NOT NULL,
	"ApprovalStatus" varchar(20) DEFAULT 'pending' NOT NULL,
	"ApprovedById" integer,
	"ApprovedDate" timestamp with time zone,
	"ApprovalNotes" text,
	"CreatedDate" timestamp with time zone DEFAULT now() NOT NULL,
	"CreatedBy" varchar(100) NOT NULL,
	"ModifiedDate" timestamp with time zone,
	"ModifiedBy" varchar(100),
	CONSTRAINT "CK_TaskTimeEntries_ApprovalStatus" CHECK (CHECK ((("ApprovalStatus")::text = ANY ((ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying])::text[])))),
	CONSTRAINT "CK_TaskTimeEntries_WorkType" CHECK (CHECK ((("WorkType")::text = ANY ((ARRAY['work'::character varying, 'break'::character varying, 'meeting'::character varying, 'review'::character varying, 'travel'::character varying, 'other'::character varying])::text[]))))
);
CREATE TABLE "TimeEntries" (
	"Id" serial PRIMARY KEY,
	"DispatchId" integer NOT NULL,
	"TechnicianId" integer,
	"StartTime" timestamp with time zone,
	"EndTime" timestamp with time zone,
	"Duration" integer,
	"Description" text,
	"ActivityType" varchar(100),
	"CreatedDate" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "user_leaves" (
	"id" serial PRIMARY KEY,
	"user_id" integer NOT NULL,
	"leave_type" varchar(50) NOT NULL,
	"start_date" date NOT NULL,
	"end_date" date NOT NULL,
	"status" varchar(20) DEFAULT 'pending' NOT NULL,
	"notes" text,
	"approved_by" integer,
	"approved_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"reason" text
);
CREATE TABLE "user_status_history" (
	"id" serial PRIMARY KEY,
	"user_id" integer NOT NULL,
	"previous_status" varchar(50),
	"new_status" varchar(50) NOT NULL,
	"reason" text,
	"changed_by" integer,
	"changed_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE "user_working_hours" (
	"id" serial PRIMARY KEY,
	"user_id" integer NOT NULL,
	"day_of_week" integer NOT NULL,
	"start_time" time NOT NULL,
	"end_time" time NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"effective_from" timestamp,
	"effective_until" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"lunch_start" time DEFAULT '12:00:00',
	"lunch_end" time DEFAULT '13:00:00',
	CONSTRAINT "user_working_hours_day_of_week_check" CHECK (CHECK (((day_of_week >= 0) AND (day_of_week <= 6))))
);
CREATE TABLE "UserPreferences" (
	"Id" serial PRIMARY KEY,
	"UserId" integer NOT NULL,
	"PreferencesJson" jsonb DEFAULT '{}' NOT NULL,
	"UpdatedAt" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE "UserRoles" (
	"Id" serial PRIMARY KEY,
	"UserId" integer NOT NULL UNIQUE,
	"RoleId" integer NOT NULL UNIQUE,
	"IsActive" boolean DEFAULT true NOT NULL,
	"AssignedAt" timestamp with time zone DEFAULT now() NOT NULL,
	"AssignedBy" varchar(100) DEFAULT 'system' NOT NULL,
	CONSTRAINT "UQ_UserRoles_User_Role" UNIQUE("UserId","RoleId")
);
CREATE TABLE "Users" (
	"Id" serial PRIMARY KEY,
	"FirstName" varchar(100) NOT NULL,
	"LastName" varchar(100) NOT NULL,
	"Email" varchar(255) NOT NULL CONSTRAINT "Users_Email_key" UNIQUE,
	"Phone" varchar(20),
	"PasswordHash" varchar(500) NOT NULL,
	"IsActive" boolean DEFAULT true NOT NULL,
	"IsDeleted" boolean DEFAULT false NOT NULL,
	"CreatedDate" timestamp with time zone DEFAULT now() NOT NULL,
	"CreatedBy" varchar(100) NOT NULL,
	"ModifiedDate" timestamp with time zone,
	"ModifiedBy" varchar(100),
	"DeletedDate" timestamp with time zone,
	"DeletedBy" varchar(100),
	"AccessToken" text,
	"RefreshToken" text,
	"TokenExpiresAt" timestamp,
	"CurrentStatus" varchar(50) DEFAULT 'offline',
	"LocationJson" text,
	"Country" varchar(2) DEFAULT 'US',
	"LastLoginAt" timestamp,
	"CreatedUser" varchar(100) DEFAULT 'system',
	"ModifyUser" varchar(100),
	"ModifyDate" timestamp,
	"Role" varchar(50) DEFAULT 'User',
	"Skills" text,
	"PhoneNumber" varchar(20)
);
CREATE TABLE "UserSkills" (
	"Id" serial PRIMARY KEY,
	"UserId" integer NOT NULL UNIQUE,
	"SkillId" integer NOT NULL UNIQUE,
	"ProficiencyLevel" varchar(20),
	"YearsOfExperience" integer,
	"Certifications" varchar(500),
	"Notes" varchar(1000),
	"IsActive" boolean DEFAULT true NOT NULL,
	"AssignedAt" timestamp with time zone DEFAULT now() NOT NULL,
	"AssignedBy" varchar(100) DEFAULT 'system' NOT NULL,
	CONSTRAINT "UQ_UserSkills_User_Skill" UNIQUE("UserId","SkillId")
);
CREATE TABLE "WorkflowApprovals" (
	"Id" serial PRIMARY KEY,
	"ExecutionId" integer NOT NULL,
	"NodeId" varchar(50) NOT NULL,
	"Title" varchar(200) NOT NULL,
	"Message" varchar(1000),
	"ApproverRole" varchar(50) NOT NULL,
	"ApprovedById" varchar(100),
	"Status" varchar(20) DEFAULT 'pending' NOT NULL,
	"ResponseNote" varchar(500),
	"TimeoutHours" integer DEFAULT 24 NOT NULL,
	"CreatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	"RespondedAt" timestamp with time zone,
	"ExpiresAt" timestamp with time zone
);
CREATE TABLE "WorkflowDefinitions" (
	"Id" serial PRIMARY KEY,
	"Name" varchar(100) NOT NULL,
	"Description" varchar(500),
	"Nodes" jsonb DEFAULT '[]' NOT NULL,
	"Edges" jsonb DEFAULT '[]' NOT NULL,
	"IsActive" boolean DEFAULT true NOT NULL,
	"Version" integer DEFAULT 1 NOT NULL,
	"CreatedBy" varchar(100),
	"CreatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	"UpdatedAt" timestamp with time zone,
	"ModifiedBy" varchar(100),
	"IsDeleted" boolean DEFAULT false NOT NULL
);
CREATE TABLE "WorkflowExecutionLogs" (
	"Id" serial PRIMARY KEY,
	"ExecutionId" integer NOT NULL,
	"NodeId" varchar(50) NOT NULL,
	"NodeType" varchar(50) NOT NULL,
	"Status" varchar(20) NOT NULL,
	"Input" jsonb,
	"Output" jsonb,
	"Error" varchar(500),
	"Duration" integer,
	"Timestamp" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE "WorkflowExecutions" (
	"Id" serial PRIMARY KEY,
	"WorkflowId" integer NOT NULL,
	"TriggerEntityType" varchar(30) NOT NULL,
	"TriggerEntityId" integer NOT NULL,
	"Status" varchar(20) DEFAULT 'running' NOT NULL,
	"CurrentNodeId" varchar(50),
	"Context" jsonb DEFAULT '{}' NOT NULL,
	"Error" varchar(1000),
	"StartedAt" timestamp with time zone DEFAULT now() NOT NULL,
	"CompletedAt" timestamp with time zone,
	"TriggeredBy" varchar(100)
);
CREATE TABLE "WorkflowProcessedEntities" (
	"Id" serial PRIMARY KEY,
	"TriggerId" integer NOT NULL,
	"EntityType" varchar(30) NOT NULL,
	"EntityId" integer NOT NULL,
	"ProcessedStatus" varchar(50),
	"ProcessedAt" timestamp DEFAULT now() NOT NULL,
	"ExecutionId" integer
);
CREATE TABLE "WorkflowReconciliationDetails" (
	"Id" serial PRIMARY KEY,
	"RunId" integer NOT NULL,
	"EntityType" varchar(30) NOT NULL,
	"EntityId" integer NOT NULL,
	"Action" varchar(100) NOT NULL,
	"CreatedEntityType" varchar(30),
	"CreatedEntityId" integer,
	"Details" varchar(500),
	"Timestamp" timestamp DEFAULT now() NOT NULL
);
CREATE TABLE "WorkflowReconciliationRuns" (
	"Id" serial PRIMARY KEY,
	"StartedAt" timestamp DEFAULT now() NOT NULL,
	"CompletedAt" timestamp,
	"Status" varchar(20) DEFAULT 'running' NOT NULL,
	"OffersFixed" integer DEFAULT 0 NOT NULL,
	"SalesFixed" integer DEFAULT 0 NOT NULL,
	"ServiceOrdersFixed" integer DEFAULT 0 NOT NULL,
	"DispatchesFixed" integer DEFAULT 0 NOT NULL,
	"TotalFixed" integer DEFAULT 0 NOT NULL,
	"Error" varchar(1000),
	"TriggeredBy" varchar(50) DEFAULT 'scheduled' NOT NULL
);
CREATE TABLE "WorkflowTriggers" (
	"Id" serial PRIMARY KEY,
	"WorkflowId" integer NOT NULL,
	"NodeId" varchar(50) NOT NULL,
	"EntityType" varchar(30) NOT NULL,
	"FromStatus" varchar(30),
	"ToStatus" varchar(30),
	"IsActive" boolean DEFAULT true NOT NULL,
	"CreatedAt" timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE "AiMessages" ADD CONSTRAINT "AiMessages_ConversationId_fkey" FOREIGN KEY ("ConversationId") REFERENCES "AiConversations"("Id") ON DELETE CASCADE;
ALTER TABLE "ArticleNotes" ADD CONSTRAINT "FK_ArticleNotes_Articles" FOREIGN KEY ("ArticleId") REFERENCES "Articles"("Id") ON DELETE CASCADE;
ALTER TABLE "calendar_events" ADD CONSTRAINT "FK_calendar_events_Contacts" FOREIGN KEY ("contact_id") REFERENCES "Contacts"("Id") ON DELETE SET NULL;
ALTER TABLE "calendar_events" ADD CONSTRAINT "FK_calendar_events_event_types" FOREIGN KEY ("Type") REFERENCES "event_types"("Id") ON DELETE RESTRICT;
ALTER TABLE "DynamicFormResponses" ADD CONSTRAINT "DynamicFormResponses_FormId_fkey" FOREIGN KEY ("FormId") REFERENCES "DynamicForms"("Id") ON DELETE CASCADE;
ALTER TABLE "EntityFormDocuments" ADD CONSTRAINT "FK_EntityFormDocuments_DynamicForms" FOREIGN KEY ("FormId") REFERENCES "DynamicForms"("Id");
ALTER TABLE "event_attendees" ADD CONSTRAINT "FK_event_attendees_calendar_events" FOREIGN KEY ("event_id") REFERENCES "calendar_events"("Id") ON DELETE CASCADE;
ALTER TABLE "event_reminders" ADD CONSTRAINT "FK_event_reminders_calendar_events" FOREIGN KEY ("event_id") REFERENCES "calendar_events"("Id") ON DELETE CASCADE;
ALTER TABLE "InstallationNotes" ADD CONSTRAINT "InstallationNotes_InstallationId_fkey" FOREIGN KEY ("InstallationId") REFERENCES "Installations"("Id") ON DELETE CASCADE;
ALTER TABLE "offer_activities" ADD CONSTRAINT "FK_offer_activities_offers" FOREIGN KEY ("offer_id") REFERENCES "offers"("id") ON DELETE CASCADE;
ALTER TABLE "offer_items" ADD CONSTRAINT "FK_offer_items_offers" FOREIGN KEY ("offer_id") REFERENCES "offers"("id") ON DELETE CASCADE;
ALTER TABLE "offers" ADD CONSTRAINT "FK_offers_Contacts" FOREIGN KEY ("contact_id") REFERENCES "Contacts"("Id") ON DELETE RESTRICT;
ALTER TABLE "RecurringTaskLogs" ADD CONSTRAINT "FK_RecurringTaskLogs_RecurringTasks" FOREIGN KEY ("RecurringTaskId") REFERENCES "RecurringTasks"("Id") ON DELETE CASCADE;
ALTER TABLE "RecurringTasks" ADD CONSTRAINT "FK_RecurringTasks_DailyTasks" FOREIGN KEY ("DailyTaskId") REFERENCES "DailyTasks"("Id") ON DELETE CASCADE;
ALTER TABLE "RecurringTasks" ADD CONSTRAINT "FK_RecurringTasks_ProjectTasks" FOREIGN KEY ("ProjectTaskId") REFERENCES "ProjectTasks"("Id") ON DELETE CASCADE;
ALTER TABLE "sale_activities" ADD CONSTRAINT "FK_sale_activities_sales" FOREIGN KEY ("sale_id") REFERENCES "sales"("id") ON DELETE CASCADE;
ALTER TABLE "sale_items" ADD CONSTRAINT "FK_sale_items_sales" FOREIGN KEY ("sale_id") REFERENCES "sales"("id") ON DELETE CASCADE;
ALTER TABLE "sales" ADD CONSTRAINT "FK_sales_Contacts" FOREIGN KEY ("contact_id") REFERENCES "Contacts"("Id") ON DELETE RESTRICT;
ALTER TABLE "sales" ADD CONSTRAINT "FK_sales_offers" FOREIGN KEY ("offer_id") REFERENCES "offers"("id") ON DELETE SET NULL;
ALTER TABLE "ServiceOrderNotes" ADD CONSTRAINT "FK_ServiceOrderNotes_ServiceOrders" FOREIGN KEY ("ServiceOrderId") REFERENCES "ServiceOrders"("Id") ON DELETE CASCADE;
ALTER TABLE "stock_transactions" ADD CONSTRAINT "stock_transactions_article_id_fkey" FOREIGN KEY ("article_id") REFERENCES "Articles"("Id") ON DELETE CASCADE;
ALTER TABLE "TaskAttachments" ADD CONSTRAINT "FK_TaskAttachments_DailyTasks" FOREIGN KEY ("DailyTaskId") REFERENCES "DailyTasks"("Id") ON DELETE CASCADE;
ALTER TABLE "TaskAttachments" ADD CONSTRAINT "FK_TaskAttachments_ProjectTasks" FOREIGN KEY ("ProjectTaskId") REFERENCES "ProjectTasks"("Id") ON DELETE CASCADE;
ALTER TABLE "TaskChecklistItems" ADD CONSTRAINT "FK_TaskChecklistItems_CompletedBy" FOREIGN KEY ("CompletedById") REFERENCES "MainAdminUsers"("Id") ON DELETE SET NULL;
ALTER TABLE "TaskChecklistItems" ADD CONSTRAINT "FK_TaskChecklistItems_TaskChecklists" FOREIGN KEY ("ChecklistId") REFERENCES "TaskChecklists"("Id") ON DELETE CASCADE;
ALTER TABLE "TaskChecklists" ADD CONSTRAINT "FK_TaskChecklists_DailyTasks" FOREIGN KEY ("DailyTaskId") REFERENCES "DailyTasks"("Id") ON DELETE CASCADE;
ALTER TABLE "TaskChecklists" ADD CONSTRAINT "FK_TaskChecklists_ProjectTasks" FOREIGN KEY ("ProjectTaskId") REFERENCES "ProjectTasks"("Id") ON DELETE CASCADE;
ALTER TABLE "TaskTimeEntries" ADD CONSTRAINT "FK_TaskTimeEntries_ApprovedBy" FOREIGN KEY ("ApprovedById") REFERENCES "MainAdminUsers"("Id");
ALTER TABLE "TaskTimeEntries" ADD CONSTRAINT "FK_TaskTimeEntries_DailyTasks" FOREIGN KEY ("DailyTaskId") REFERENCES "DailyTasks"("Id") ON DELETE SET NULL;
ALTER TABLE "TaskTimeEntries" ADD CONSTRAINT "FK_TaskTimeEntries_ProjectTasks" FOREIGN KEY ("ProjectTaskId") REFERENCES "ProjectTasks"("Id") ON DELETE SET NULL;
ALTER TABLE "TaskTimeEntries" ADD CONSTRAINT "FK_TaskTimeEntries_Users" FOREIGN KEY ("UserId") REFERENCES "MainAdminUsers"("Id");
ALTER TABLE "TimeEntries" ADD CONSTRAINT "TimeEntries_DispatchId_fkey" FOREIGN KEY ("DispatchId") REFERENCES "Dispatches"("Id") ON DELETE CASCADE;
ALTER TABLE "UserPreferences" ADD CONSTRAINT "FK_UserPreferences_Users" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE CASCADE;
ALTER TABLE "UserRoles" ADD CONSTRAINT "FK_UserRoles_Roles" FOREIGN KEY ("RoleId") REFERENCES "Roles"("Id") ON DELETE CASCADE;
ALTER TABLE "UserRoles" ADD CONSTRAINT "FK_UserRoles_Users" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE CASCADE;
ALTER TABLE "UserSkills" ADD CONSTRAINT "FK_UserSkills_Skills" FOREIGN KEY ("SkillId") REFERENCES "Skills"("Id") ON DELETE CASCADE;
ALTER TABLE "UserSkills" ADD CONSTRAINT "FK_UserSkills_Users" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE CASCADE;
ALTER TABLE "WorkflowApprovals" ADD CONSTRAINT "WorkflowApprovals_ExecutionId_fkey" FOREIGN KEY ("ExecutionId") REFERENCES "WorkflowExecutions"("Id") ON DELETE CASCADE;
ALTER TABLE "WorkflowExecutionLogs" ADD CONSTRAINT "WorkflowExecutionLogs_ExecutionId_fkey" FOREIGN KEY ("ExecutionId") REFERENCES "WorkflowExecutions"("Id") ON DELETE CASCADE;
ALTER TABLE "WorkflowExecutions" ADD CONSTRAINT "WorkflowExecutions_WorkflowId_fkey" FOREIGN KEY ("WorkflowId") REFERENCES "WorkflowDefinitions"("Id") ON DELETE CASCADE;
ALTER TABLE "WorkflowProcessedEntities" ADD CONSTRAINT "WorkflowProcessedEntities_ExecutionId_fkey" FOREIGN KEY ("ExecutionId") REFERENCES "WorkflowExecutions"("Id") ON DELETE SET NULL;
ALTER TABLE "WorkflowProcessedEntities" ADD CONSTRAINT "WorkflowProcessedEntities_TriggerId_fkey" FOREIGN KEY ("TriggerId") REFERENCES "WorkflowTriggers"("Id") ON DELETE CASCADE;
ALTER TABLE "WorkflowReconciliationDetails" ADD CONSTRAINT "WorkflowReconciliationDetails_RunId_fkey" FOREIGN KEY ("RunId") REFERENCES "WorkflowReconciliationRuns"("Id") ON DELETE CASCADE;
ALTER TABLE "WorkflowTriggers" ADD CONSTRAINT "WorkflowTriggers_WorkflowId_fkey" FOREIGN KEY ("WorkflowId") REFERENCES "WorkflowDefinitions"("Id") ON DELETE CASCADE;
CREATE UNIQUE INDEX "PK___EFMigrationsHistory" ON "__EFMigrationsHistory" ("MigrationId");
CREATE UNIQUE INDEX "AiConversations_pkey" ON "AiConversations" ("Id");
CREATE INDEX "IX_AiConversations_LastMessageAt" ON "AiConversations" ("LastMessageAt");
CREATE INDEX "IX_AiConversations_UserId" ON "AiConversations" ("UserId");
CREATE INDEX "IX_AiConversations_UserId_IsDeleted" ON "AiConversations" ("UserId","IsDeleted");
CREATE UNIQUE INDEX "AiMessages_pkey" ON "AiMessages" ("Id");
CREATE INDEX "IX_AiMessages_ConversationId" ON "AiMessages" ("ConversationId");
CREATE INDEX "IX_AiMessages_CreatedAt" ON "AiMessages" ("CreatedAt");
CREATE UNIQUE INDEX "PK_ArticleCategories" ON "ArticleCategories" ("Id");
CREATE UNIQUE INDEX "ArticleNotes_pkey" ON "ArticleNotes" ("Id");
CREATE INDEX "idx_article_notes_article_id" ON "ArticleNotes" ("ArticleId");
CREATE INDEX "idx_articles_type" ON "Articles" ("Type");
CREATE UNIQUE INDEX "PK_Articles" ON "Articles" ("Id");
CREATE INDEX "IX_Attachments_DispatchId" ON "Attachments" ("DispatchId");
CREATE UNIQUE INDEX "PK_Attachments" ON "Attachments" ("Id");
CREATE UNIQUE INDEX "calendar_events_pkey" ON "calendar_events" ("Id");
CREATE UNIQUE INDEX "PK_CalendarEvents" ON "CalendarEvents" ("Id");
CREATE INDEX "idx_contactnotes_contact" ON "ContactNotes" ("ContactId");
CREATE INDEX "idx_contactnotes_contactid" ON "ContactNotes" ("ContactId");
CREATE UNIQUE INDEX "PK_ContactNotes" ON "ContactNotes" ("Id");
CREATE INDEX "idx_contacts_cin" ON "Contacts" ("Cin");
CREATE INDEX "idx_contacts_company" ON "Contacts" ("Company");
CREATE INDEX "idx_contacts_email" ON "Contacts" ("Email");
CREATE INDEX "idx_contacts_has_location" ON "Contacts" ("HasLocation");
CREATE INDEX "idx_contacts_matricule" ON "Contacts" ("MatriculeFiscale");
CREATE INDEX "idx_contacts_name" ON "Contacts" ("Name");
CREATE INDEX "idx_contacts_status" ON "Contacts" ("Status");
CREATE UNIQUE INDEX "PK_Contacts" ON "Contacts" ("Id");
CREATE INDEX "idx_contacttagassignments_contact" ON "ContactTagAssignments" ("ContactId");
CREATE INDEX "idx_contacttagassignments_tag" ON "ContactTagAssignments" ("TagId");
CREATE UNIQUE INDEX "PK_ContactTagAssignments" ON "ContactTagAssignments" ("Id");
CREATE UNIQUE INDEX "PK_ContactTags" ON "ContactTags" ("Id");
CREATE UNIQUE INDEX "PK_Currencies" ON "Currencies" ("Id");
CREATE UNIQUE INDEX "PK_DailyTasks" ON "DailyTasks" ("Id");
CREATE INDEX "idx_dispatches_not_deleted" ON "Dispatches" ("IsDeleted");
CREATE UNIQUE INDEX "PK_Dispatches" ON "Dispatches" ("Id");
CREATE UNIQUE INDEX "PK_DispatchHistory" ON "DispatchHistory" ("Id");
CREATE UNIQUE INDEX "PK_DispatchTechnicians" ON "DispatchTechnicians" ("Id");
CREATE UNIQUE INDEX "Documents_pkey" ON "Documents" ("Id");
CREATE INDEX "idx_documents_category" ON "Documents" ("Category");
CREATE INDEX "idx_documents_module" ON "Documents" ("ModuleType","ModuleId");
CREATE INDEX "idx_documents_uploaded_at" ON "Documents" ("UploadedAt");
CREATE INDEX "idx_documents_uploaded_by" ON "Documents" ("UploadedBy");
CREATE UNIQUE INDEX "DynamicFormResponses_pkey" ON "DynamicFormResponses" ("Id");
CREATE INDEX "IX_DynamicFormResponses_FormId" ON "DynamicFormResponses" ("FormId");
CREATE UNIQUE INDEX "DynamicForms_pkey" ON "DynamicForms" ("Id");
CREATE UNIQUE INDEX "DynamicForms_PublicSlug_key" ON "DynamicForms" ("PublicSlug");
CREATE INDEX "idx_dynamicforms_publicslug" ON "DynamicForms" ("PublicSlug");
CREATE INDEX "idx_dynamicforms_thankyousettings" ON "DynamicForms" USING gin ("ThankYouSettings");
CREATE INDEX "IX_DynamicForms_PublicSlug" ON "DynamicForms" ("PublicSlug");
CREATE INDEX "IX_DynamicForms_Status" ON "DynamicForms" ("Status");
CREATE UNIQUE INDEX "EntityFormDocuments_pkey" ON "EntityFormDocuments" ("Id");
CREATE INDEX "IX_EntityFormDocuments_Entity" ON "EntityFormDocuments" ("EntityType","EntityId");
CREATE INDEX "IX_EntityFormDocuments_FormId" ON "EntityFormDocuments" ("FormId");
CREATE INDEX "IX_EntityFormDocuments_Status" ON "EntityFormDocuments" ("Status");
CREATE UNIQUE INDEX "event_attendees_pkey" ON "event_attendees" ("Id");
CREATE UNIQUE INDEX "event_reminders_pkey" ON "event_reminders" ("Id");
CREATE UNIQUE INDEX "event_types_pkey" ON "event_types" ("Id");
CREATE UNIQUE INDEX "PK_EventAttendees" ON "EventAttendees" ("Id");
CREATE UNIQUE INDEX "PK_EventReminders" ON "EventReminders" ("Id");
CREATE UNIQUE INDEX "PK_EventTypes" ON "EventTypes" ("Id");
CREATE INDEX "IX_Expenses_DispatchId" ON "Expenses" ("DispatchId");
CREATE UNIQUE INDEX "PK_Expenses" ON "Expenses" ("Id");
CREATE INDEX "idx_installationnotes_installationid" ON "InstallationNotes" ("InstallationId");
CREATE UNIQUE INDEX "InstallationNotes_pkey" ON "InstallationNotes" ("Id");
CREATE UNIQUE INDEX "PK_Installations" ON "Installations" ("Id");
CREATE UNIQUE INDEX "PK_InventoryTransactions" ON "InventoryTransactions" ("Id");
CREATE UNIQUE INDEX "PK_Locations" ON "Locations" ("Id");
CREATE UNIQUE INDEX "PK_LookupItems" ON "LookupItems" ("Id");
CREATE INDEX "idx_mainadminusers_email" ON "MainAdminUsers" ("Email");
CREATE UNIQUE INDEX "PK_MainAdminUsers" ON "MainAdminUsers" ("Id");
CREATE UNIQUE INDEX "PK_MaintenanceHistory" ON "MaintenanceHistory" ("Id");
CREATE INDEX "IX_MaterialUsage_DispatchId" ON "MaterialUsage" ("DispatchId");
CREATE UNIQUE INDEX "PK_MaterialUsage" ON "MaterialUsage" ("Id");
CREATE INDEX "IX_Notes_DispatchId" ON "Notes" ("DispatchId");
CREATE UNIQUE INDEX "PK_Notes" ON "Notes" ("Id");
CREATE UNIQUE INDEX "Notifications_pkey" ON "Notifications" ("Id");
CREATE UNIQUE INDEX "offer_activities_pkey" ON "offer_activities" ("id");
CREATE UNIQUE INDEX "offer_items_pkey" ON "offer_items" ("id");
CREATE UNIQUE INDEX "PK_OfferActivities" ON "OfferActivities" ("Id");
CREATE UNIQUE INDEX "PK_OfferItems" ON "OfferItems" ("Id");
CREATE INDEX "idx_offers_contact_has_location" ON "Offers" ("ContactHasLocation");
CREATE UNIQUE INDEX "PK_Offers" ON "Offers" ("Id");
CREATE UNIQUE INDEX "offers_pkey" ON "offers" ("id");
CREATE INDEX "idx_pdf_settings_module" ON "PdfSettings" ("Module");
CREATE UNIQUE INDEX "PdfSettings_Module_key" ON "PdfSettings" ("Module");
CREATE UNIQUE INDEX "PdfSettings_pkey" ON "PdfSettings" ("Id");
CREATE UNIQUE INDEX "PK_ProjectColumns" ON "ProjectColumns" ("Id");
CREATE UNIQUE INDEX "PK_Projects" ON "Projects" ("Id");
CREATE UNIQUE INDEX "PK_ProjectTasks" ON "ProjectTasks" ("Id");
CREATE INDEX "IX_RecurringTaskLogs_GeneratedDate" ON "RecurringTaskLogs" ("GeneratedDate");
CREATE INDEX "IX_RecurringTaskLogs_RecurringTaskId" ON "RecurringTaskLogs" ("RecurringTaskId");
CREATE UNIQUE INDEX "RecurringTaskLogs_pkey" ON "RecurringTaskLogs" ("Id");
CREATE INDEX "IX_RecurringTasks_DailyTaskId" ON "RecurringTasks" ("DailyTaskId");
CREATE INDEX "IX_RecurringTasks_IsActive" ON "RecurringTasks" ("IsActive");
CREATE INDEX "IX_RecurringTasks_NextOccurrence" ON "RecurringTasks" ("NextOccurrence");
CREATE INDEX "IX_RecurringTasks_ProjectTaskId" ON "RecurringTasks" ("ProjectTaskId");
CREATE UNIQUE INDEX "RecurringTasks_pkey" ON "RecurringTasks" ("Id");
CREATE INDEX "IX_RolePermissions_Module_Action" ON "RolePermissions" ("Module","Action");
CREATE INDEX "IX_RolePermissions_RoleId" ON "RolePermissions" ("RoleId");
CREATE UNIQUE INDEX "RolePermissions_pkey" ON "RolePermissions" ("Id");
CREATE UNIQUE INDEX "UQ_RolePermissions_Role_Module_Action" ON "RolePermissions" ("RoleId","Module","Action");
CREATE INDEX "idx_roles_isactive" ON "Roles" ("IsActive");
CREATE INDEX "idx_roles_name" ON "Roles" ("Name");
CREATE UNIQUE INDEX "PK_Roles" ON "Roles" ("Id");
CREATE INDEX "idx_roleskills_roleid" ON "RoleSkills" ("RoleId");
CREATE INDEX "idx_roleskills_skillid" ON "RoleSkills" ("SkillId");
CREATE UNIQUE INDEX "PK_RoleSkills" ON "RoleSkills" ("Id");
CREATE UNIQUE INDEX "sale_activities_pkey" ON "sale_activities" ("id");
CREATE UNIQUE INDEX "sale_items_pkey" ON "sale_items" ("id");
CREATE UNIQUE INDEX "PK_SaleActivities" ON "SaleActivities" ("Id");
CREATE UNIQUE INDEX "PK_SaleItems" ON "SaleItems" ("Id");
CREATE UNIQUE INDEX "sales_pkey" ON "sales" ("id");
CREATE INDEX "idx_sales_contact_has_location" ON "Sales" ("ContactHasLocation");
CREATE UNIQUE INDEX "PK_Sales" ON "Sales" ("Id");
CREATE UNIQUE INDEX "ServiceOrderExpenses_pkey" ON "ServiceOrderExpenses" ("Id");
CREATE UNIQUE INDEX "PK_ServiceOrderJobs" ON "ServiceOrderJobs" ("Id");
CREATE UNIQUE INDEX "ServiceOrderMaterials_pkey" ON "ServiceOrderMaterials" ("Id");
CREATE INDEX "IX_ServiceOrderNotes_ServiceOrderId" ON "ServiceOrderNotes" ("ServiceOrderId");
CREATE UNIQUE INDEX "ServiceOrderNotes_pkey" ON "ServiceOrderNotes" ("Id");
CREATE INDEX "idx_service_orders_contact_has_location" ON "ServiceOrders" ("ContactHasLocation");
CREATE UNIQUE INDEX "PK_ServiceOrders" ON "ServiceOrders" ("Id");
CREATE UNIQUE INDEX "ServiceOrderTimeEntries_pkey" ON "ServiceOrderTimeEntries" ("Id");
CREATE INDEX "idx_skills_category" ON "Skills" ("Category");
CREATE INDEX "idx_skills_isactive" ON "Skills" ("IsActive");
CREATE INDEX "idx_skills_name" ON "Skills" ("Name");
CREATE UNIQUE INDEX "PK_Skills" ON "Skills" ("Id");
CREATE INDEX "idx_stock_transactions_article_id" ON "stock_transactions" ("article_id");
CREATE INDEX "idx_stock_transactions_created_at" ON "stock_transactions" ("created_at");
CREATE INDEX "idx_stock_transactions_performed_by" ON "stock_transactions" ("performed_by");
CREATE INDEX "idx_stock_transactions_reference" ON "stock_transactions" ("reference_type","reference_id");
CREATE INDEX "idx_stock_transactions_type" ON "stock_transactions" ("transaction_type");
CREATE UNIQUE INDEX "stock_transactions_pkey" ON "stock_transactions" ("id");
CREATE UNIQUE INDEX "SystemLogs_pkey" ON "SystemLogs" ("Id");
CREATE UNIQUE INDEX "TaskAttachments_pkey" ON "TaskAttachments" ("Id");
CREATE INDEX "IX_TaskChecklistItems_ChecklistId" ON "TaskChecklistItems" ("ChecklistId");
CREATE UNIQUE INDEX "TaskChecklistItems_pkey" ON "TaskChecklistItems" ("Id");
CREATE INDEX "IX_TaskChecklists_DailyTaskId" ON "TaskChecklists" ("DailyTaskId");
CREATE INDEX "IX_TaskChecklists_ProjectTaskId" ON "TaskChecklists" ("ProjectTaskId");
CREATE UNIQUE INDEX "TaskChecklists_pkey" ON "TaskChecklists" ("Id");
CREATE UNIQUE INDEX "TaskComments_pkey" ON "TaskComments" ("Id");
CREATE INDEX "IX_TaskTimeEntries_ApprovalStatus" ON "TaskTimeEntries" ("ApprovalStatus");
CREATE INDEX "IX_TaskTimeEntries_DailyTaskId" ON "TaskTimeEntries" ("DailyTaskId");
CREATE INDEX "IX_TaskTimeEntries_ProjectTaskId" ON "TaskTimeEntries" ("ProjectTaskId");
CREATE INDEX "IX_TaskTimeEntries_StartTime" ON "TaskTimeEntries" ("StartTime");
CREATE INDEX "IX_TaskTimeEntries_UserId" ON "TaskTimeEntries" ("UserId");
CREATE UNIQUE INDEX "TaskTimeEntries_pkey" ON "TaskTimeEntries" ("Id");
CREATE INDEX "IX_TimeEntries_DispatchId" ON "TimeEntries" ("DispatchId");
CREATE UNIQUE INDEX "TimeEntries_pkey" ON "TimeEntries" ("Id");
CREATE INDEX "idx_user_leaves_dates" ON "user_leaves" ("start_date","end_date");
CREATE INDEX "idx_user_leaves_status" ON "user_leaves" ("status");
CREATE INDEX "idx_user_leaves_user_id" ON "user_leaves" ("user_id");
CREATE UNIQUE INDEX "user_leaves_pkey" ON "user_leaves" ("id");
CREATE INDEX "idx_user_status_history_changed_at" ON "user_status_history" ("changed_at");
CREATE INDEX "idx_user_status_history_user_id" ON "user_status_history" ("user_id");
CREATE UNIQUE INDEX "user_status_history_pkey" ON "user_status_history" ("id");
CREATE INDEX "idx_user_working_hours_active" ON "user_working_hours" ("is_active");
CREATE INDEX "idx_user_working_hours_day" ON "user_working_hours" ("day_of_week");
CREATE INDEX "idx_user_working_hours_user_id" ON "user_working_hours" ("user_id");
CREATE UNIQUE INDEX "user_working_hours_pkey" ON "user_working_hours" ("id");
CREATE INDEX "idx_userpreferences_userid" ON "UserPreferences" ("UserId");
CREATE UNIQUE INDEX "UserPreferences_pkey" ON "UserPreferences" ("Id");
CREATE INDEX "idx_userroles_roleid" ON "UserRoles" ("RoleId");
CREATE INDEX "idx_userroles_userid" ON "UserRoles" ("UserId");
CREATE UNIQUE INDEX "UQ_UserRoles_User_Role" ON "UserRoles" ("UserId","RoleId");
CREATE UNIQUE INDEX "UserRoles_pkey" ON "UserRoles" ("Id");
CREATE INDEX "idx_users_email" ON "Users" ("Email");
CREATE INDEX "idx_users_isactive" ON "Users" ("IsActive");
CREATE INDEX "idx_users_isdeleted" ON "Users" ("IsDeleted");
CREATE UNIQUE INDEX "Users_Email_key" ON "Users" ("Email");
CREATE UNIQUE INDEX "Users_pkey" ON "Users" ("Id");
CREATE INDEX "idx_userskills_skillid" ON "UserSkills" ("SkillId");
CREATE INDEX "idx_userskills_userid" ON "UserSkills" ("UserId");
CREATE UNIQUE INDEX "UQ_UserSkills_User_Skill" ON "UserSkills" ("UserId","SkillId");
CREATE UNIQUE INDEX "UserSkills_pkey" ON "UserSkills" ("Id");
CREATE INDEX "IX_WorkflowApprovals_ExecutionId" ON "WorkflowApprovals" ("ExecutionId");
CREATE INDEX "IX_WorkflowApprovals_Status" ON "WorkflowApprovals" ("Status");
CREATE UNIQUE INDEX "WorkflowApprovals_pkey" ON "WorkflowApprovals" ("Id");
CREATE UNIQUE INDEX "WorkflowDefinitions_pkey" ON "WorkflowDefinitions" ("Id");
CREATE INDEX "IX_WorkflowExecutionLogs_ExecutionId" ON "WorkflowExecutionLogs" ("ExecutionId");
CREATE UNIQUE INDEX "WorkflowExecutionLogs_pkey" ON "WorkflowExecutionLogs" ("Id");
CREATE INDEX "IX_WorkflowExecutions_StartedAt" ON "WorkflowExecutions" ("StartedAt");
CREATE INDEX "IX_WorkflowExecutions_Status" ON "WorkflowExecutions" ("Status");
CREATE INDEX "IX_WorkflowExecutions_WorkflowId" ON "WorkflowExecutions" ("WorkflowId");
CREATE UNIQUE INDEX "WorkflowExecutions_pkey" ON "WorkflowExecutions" ("Id");
CREATE INDEX "idx_workflow_processed_entity" ON "WorkflowProcessedEntities" ("EntityType","EntityId");
CREATE INDEX "idx_workflow_processed_trigger" ON "WorkflowProcessedEntities" ("TriggerId");
CREATE UNIQUE INDEX "idx_workflow_processed_unique" ON "WorkflowProcessedEntities" ("TriggerId","EntityType","EntityId","ProcessedStatus");
CREATE UNIQUE INDEX "WorkflowProcessedEntities_pkey" ON "WorkflowProcessedEntities" ("Id");
CREATE INDEX "idx_reconciliation_details_entity" ON "WorkflowReconciliationDetails" ("EntityType","EntityId");
CREATE INDEX "idx_reconciliation_details_run" ON "WorkflowReconciliationDetails" ("RunId");
CREATE UNIQUE INDEX "WorkflowReconciliationDetails_pkey" ON "WorkflowReconciliationDetails" ("Id");
CREATE INDEX "idx_reconciliation_runs_started" ON "WorkflowReconciliationRuns" ("StartedAt");
CREATE UNIQUE INDEX "WorkflowReconciliationRuns_pkey" ON "WorkflowReconciliationRuns" ("Id");
CREATE INDEX "IX_WorkflowTriggers_EntityType" ON "WorkflowTriggers" ("EntityType");
CREATE INDEX "IX_WorkflowTriggers_WorkflowId" ON "WorkflowTriggers" ("WorkflowId");
CREATE UNIQUE INDEX "WorkflowTriggers_pkey" ON "WorkflowTriggers" ("Id");