-- Fix individual UNIQUE constraints that should only be composite.
-- These were likely generated by EF Core or a migration tool that emitted
-- per-column UNIQUE in addition to the composite UNIQUE, which makes it
-- impossible to insert more than one row sharing TenantId / ArticleId /
-- SupplierId / DispatchId / JobId / entity_name / period_key.
--
-- Run once against each tenant database.

-- ────────────────────────────────────────────────────────────────────────────
-- 1. ArticleSuppliers
--    Problem: individual UNIQUE on TenantId, ArticleId, and SupplierId means
--    only one row per company (one article, one supplier) in the whole table.
--    Correct: composite UNIQUE(TenantId, ArticleId, SupplierId) already exists.
-- ────────────────────────────────────────────────────────────────────────────
ALTER TABLE "ArticleSuppliers" DROP CONSTRAINT IF EXISTS "ArticleSuppliers_TenantId_key";
ALTER TABLE "ArticleSuppliers" DROP CONSTRAINT IF EXISTS "ArticleSuppliers_ArticleId_key";
ALTER TABLE "ArticleSuppliers" DROP CONSTRAINT IF EXISTS "ArticleSuppliers_SupplierId_key";
-- Composite UNIQUE(TenantId, ArticleId, SupplierId) is kept as-is:
-- "ArticleSuppliers_TenantId_ArticleId_SupplierId_key"

-- ────────────────────────────────────────────────────────────────────────────
-- 2. DispatchJobs
--    Problem: individual UNIQUE on DispatchId and JobId means each dispatch
--    can have at most one job row, and each job can appear in at most one row.
--    Correct: composite UNIQUE(DispatchId, JobId) already exists.
-- ────────────────────────────────────────────────────────────────────────────
ALTER TABLE "DispatchJobs" DROP CONSTRAINT IF EXISTS "DispatchJobs_DispatchId_key";
ALTER TABLE "DispatchJobs" DROP CONSTRAINT IF EXISTS "DispatchJobs_JobId_key";
-- Composite UNIQUE(DispatchId, JobId) is kept as-is:
-- "DispatchJobs_DispatchId_JobId_key"

-- ────────────────────────────────────────────────────────────────────────────
-- 3. NumberSequences
--    Problem: individual UNIQUE on entity_name and period_key means the table
--    can only ever have one entity_name value (so the second document type
--    that gets a sequence will fail) and only one period_key value (so yearly
--    reset sequences break after the first year).
--    Correct: composite UNIQUE(entity_name, period_key) already exists.
--    Also add TenantId to the composite so each tenant has its own counters.
-- ────────────────────────────────────────────────────────────────────────────
ALTER TABLE "NumberSequences" DROP CONSTRAINT IF EXISTS "NumberSequences_entity_name_key";
ALTER TABLE "NumberSequences" DROP CONSTRAINT IF EXISTS "NumberSequences_period_key_key";

-- The existing composite (entity_name, period_key) is kept as-is because
-- NumberingService raw SQL uses ON CONFLICT (entity_name, period_key).
-- Each project already has its own database (subdomain isolation), so the
-- composite without TenantId is sufficient for cross-company uniqueness.
-- "uq_number_sequences_entity_period" is preserved.
