// Per-module API endpoints + backend entities/tables.
// Curated from src/services/api/* and module-level api files.
// Endpoints are shown grouped by HTTP verb where useful; resource names
// double as backend entity / DB table names.

export type ApiEndpoint = { method: string; path: string; description?: string };

export const MODULE_APIS: Record<string, ApiEndpoint[]> = {
  dashboard: [
    { method: "GET", path: "/api/SystemLogs/statistics", description: "Activity statistics for dashboard widgets" },
    { method: "GET", path: "/api/Notifications/unread-count", description: "Unread notifications badge" },
    { method: "GET", path: "/api/Dashboards", description: "List user dashboards" },
    { method: "GET", path: "/api/Dashboards/{id}", description: "Load a dashboard layout" },
    { method: "POST", path: "/api/Dashboards", description: "Create dashboard" },
    { method: "PUT", path: "/api/Dashboards/{id}", description: "Update dashboard widgets/layout" },
    { method: "DELETE", path: "/api/Dashboards/{id}", description: "Delete dashboard" },
  ],
  contacts: [
    { method: "GET", path: "/api/Contacts", description: "Paged list of contacts (filter/sort)" },
    { method: "GET", path: "/api/Contacts/{id}", description: "Get a single contact" },
    { method: "POST", path: "/api/Contacts", description: "Create person or company contact" },
    { method: "PUT", path: "/api/Contacts/{id}", description: "Update contact" },
    { method: "DELETE", path: "/api/Contacts/{id}", description: "Delete contact" },
    { method: "GET", path: "/api/Contacts/search", description: "Full-text search" },
    { method: "GET", path: "/api/Contacts/exists/{email}", description: "Email uniqueness check" },
    { method: "POST", path: "/api/Contacts/import", description: "Bulk CSV/Excel import" },
    { method: "POST", path: "/api/Contacts/{contactId}/tags/{tagId}", description: "Attach tag" },
    { method: "DELETE", path: "/api/Contacts/{contactId}/tags/{tagId}", description: "Detach tag" },
    { method: "GET/POST/PUT/DELETE", path: "/api/ContactNotes", description: "Notes attached to a contact" },
    { method: "GET/POST/DELETE", path: "/api/ContactTags", description: "Tag catalog" },
  ],
  offers: [
    { method: "GET", path: "/api/offers", description: "List quotes/offers" },
    { method: "GET", path: "/api/offers/{id}", description: "Offer detail with line items" },
    { method: "POST", path: "/api/offers", description: "Create offer" },
    { method: "PUT", path: "/api/offers/{id}", description: "Update offer" },
    { method: "DELETE", path: "/api/offers/{id}", description: "Delete offer" },
    { method: "POST", path: "/api/offers/import", description: "Bulk import offers" },
    { method: "POST", path: "/api/sales/from-offer/{offerId}", description: "Convert offer to sale/invoice" },
  ],
  sales: [
    { method: "GET", path: "/api/sales", description: "List sales/invoices" },
    { method: "GET", path: "/api/sales/{id}", description: "Sale detail" },
    { method: "POST", path: "/api/sales", description: "Create sale/invoice" },
    { method: "PUT", path: "/api/sales/{id}", description: "Update sale" },
    { method: "DELETE", path: "/api/sales/{id}", description: "Delete sale" },
    { method: "GET", path: "/api/sales/stats", description: "Sales aggregates" },
    { method: "POST", path: "/api/service-orders/from-sale/{saleId}", description: "Generate service orders from sale" },
  ],
  deals: [
    { method: "GET", path: "/api/offers", description: "Offers feeding the pipeline" },
    { method: "GET", path: "/api/sales", description: "Won deals sourced from sales" },
    { method: "PUT", path: "/api/offers/{id}", description: "Move deal stage / update probability" },
  ],
  articles: [
    { method: "GET", path: "/api/articles", description: "List articles (products + services)" },
    { method: "GET", path: "/api/articles/{id}", description: "Article detail" },
    { method: "POST", path: "/api/articles", description: "Create article" },
    { method: "PUT", path: "/api/articles/{id}", description: "Update article" },
    { method: "DELETE", path: "/api/articles/{id}", description: "Delete article" },
    { method: "POST", path: "/api/articles/batch", description: "Bulk operations" },
    { method: "POST", path: "/api/articles/import", description: "Bulk import" },
    { method: "GET", path: "/api/articles/categories", description: "Categories tree" },
    { method: "GET", path: "/api/articles/groups", description: "Pricing/grouping" },
    { method: "GET/POST/PUT/DELETE", path: "/api/ArticleNotes", description: "Notes attached to an article" },
    { method: "GET/POST", path: "/api/article-suppliers", description: "Article ↔ supplier linkage and pricing" },
  ],
  "inventory-services": [
    { method: "GET", path: "/api/articles?type=service", description: "Service-type articles" },
    { method: "POST", path: "/api/articles", description: "Create service item" },
    { method: "PUT", path: "/api/articles/{id}", description: "Update service item (rate, unit, duration)" },
  ],
  "stock-management": [
    { method: "GET", path: "/api/articles/locations", description: "Warehouse / stock locations" },
    { method: "GET", path: "/api/articles/transactions", description: "Movement history" },
    { method: "POST", path: "/api/stock-transactions/add", description: "Stock-in transaction" },
    { method: "POST", path: "/api/stock-transactions/remove", description: "Stock-out transaction" },
    { method: "GET", path: "/api/stock-transactions/article/{id}", description: "Transactions for one article" },
    { method: "GET", path: "/api/stock/anomaly-detection", description: "AI anomaly scan" },
    { method: "GET", path: "/api/stock/demand-forecast", description: "Demand forecasting" },
  ],
  purchases: [
    { method: "GET", path: "/api/purchase-orders", description: "List purchase orders" },
    { method: "GET", path: "/api/purchase-orders/{id}", description: "PO detail" },
    { method: "POST", path: "/api/purchase-orders", description: "Create PO" },
    { method: "PUT", path: "/api/purchase-orders/{id}", description: "Update PO" },
    { method: "DELETE", path: "/api/purchase-orders/{id}", description: "Delete PO" },
    { method: "GET", path: "/api/purchase-orders/stats", description: "Procurement KPIs" },
    { method: "GET/POST/PUT", path: "/api/goods-receipts", description: "Goods receipt notes" },
    { method: "GET/POST/PUT", path: "/api/supplier-invoices", description: "Supplier invoices / 3-way match" },
  ],
  hr: [
    { method: "GET/POST/PUT/DELETE", path: "/api/hr/employees", description: "Employee records" },
    { method: "GET/POST/PUT/DELETE", path: "/api/hr/departments", description: "Departments / org units" },
    { method: "GET/POST/PUT", path: "/api/hr/contracts/expiring", description: "Contracts management" },
    { method: "GET/POST", path: "/api/hr/attendance", description: "Attendance tracking + import" },
    { method: "GET", path: "/api/hr/attendance/settings", description: "Attendance rules" },
    { method: "GET/POST/PUT", path: "/api/hr/leaves/balances", description: "Leave balances and active leaves" },
    { method: "GET/POST", path: "/api/hr/payroll/runs", description: "Payroll run lifecycle" },
    { method: "POST", path: "/api/hr/payroll/run", description: "Trigger payroll run" },
    { method: "GET", path: "/api/hr/payroll/payslip/{id}", description: "Generate payslip PDF" },
    { method: "GET/POST/PUT", path: "/api/hr/bonuses", description: "Bonuses & one-off pay" },
    { method: "GET", path: "/api/hr/cnss/declaration", description: "CNSS social-security declaration" },
    { method: "GET/POST/PUT", path: "/api/hr/cnss/rates", description: "CNSS rate brackets" },
    { method: "GET/POST/PUT/DELETE", path: "/api/hr/holidays", description: "Public holidays" },
    { method: "GET/POST/PUT", path: "/api/hr/performance/cycles", description: "Performance review cycles" },
    { method: "GET/POST/PUT", path: "/api/hr/performance/goals", description: "Goals (OKR/SMART)" },
    { method: "GET/POST/PUT", path: "/api/hr/performance/reviews", description: "Review forms" },
    { method: "GET/POST/PUT", path: "/api/hr/recruitment/openings", description: "Job openings" },
    { method: "GET/POST/PUT", path: "/api/hr/recruitment/applicants", description: "Applicants pipeline" },
    { method: "GET/POST/PUT", path: "/api/hr/recruitment/interviews", description: "Interview scheduling" },
    { method: "GET", path: "/api/hr/recruitment/dashboard", description: "Recruitment KPIs" },
    { method: "GET/POST", path: "/api/hr/documents", description: "HR documents" },
    { method: "GET", path: "/api/hr/audit", description: "HR audit log" },
    { method: "GET", path: "/api/hr/reports/employee-cost", description: "Employee cost report" },
  ],
  field: [
    { method: "GET", path: "/api/dispatches", description: "List dispatches" },
    { method: "POST", path: "/api/dispatches", description: "Create dispatch" },
    { method: "PUT", path: "/api/dispatches/{id}", description: "Update dispatch" },
    { method: "POST", path: "/api/dispatches/from-installation", description: "Dispatch from installation" },
    { method: "POST", path: "/api/dispatches/from-job/{jobId}", description: "Dispatch from a job" },
    { method: "GET", path: "/api/dispatches/statistics", description: "Field operations KPIs" },
    { method: "GET/POST/PUT/DELETE", path: "/api/installations", description: "Installations registry" },
    { method: "POST", path: "/api/installations/import", description: "Bulk import" },
    { method: "GET/POST/PUT/DELETE", path: "/api/InstallationNotes", description: "Notes per installation" },
    { method: "GET/POST/PUT/DELETE", path: "/api/service-orders", description: "Service orders / work orders" },
    { method: "GET", path: "/api/service-orders/statistics", description: "Service order KPIs" },
  ],
  scheduling: [
    { method: "GET/POST/PUT/DELETE", path: "/api/planning/schedule", description: "Technician schedule entries" },
    { method: "GET/POST/PUT/DELETE", path: "/api/planning/leaves", description: "Leaves and unavailability" },
    { method: "GET", path: "/api/dispatches", description: "Jobs to plan" },
    { method: "GET", path: "/api/settings/working-hours", description: "Working-hours config" },
    { method: "GET/PUT", path: "/api/settings/planner", description: "Planner display preferences" },
  ],
  tasks: [
    { method: "GET", path: "/api/Tasks/project-task", description: "List project tasks" },
    { method: "GET", path: "/api/Tasks/daily-task", description: "List daily tasks" },
    { method: "GET", path: "/api/Tasks/{id}", description: "Task detail" },
    { method: "POST", path: "/api/Tasks/project-task", description: "Create project task" },
    { method: "POST", path: "/api/Tasks/daily-task", description: "Create daily task" },
    { method: "PUT", path: "/api/Tasks/{id}", description: "Update task" },
    { method: "DELETE", path: "/api/Tasks/{id}", description: "Delete task" },
    { method: "GET", path: "/api/Tasks/search", description: "Search tasks" },
    { method: "GET", path: "/api/Tasks/overdue", description: "Overdue tasks" },
    { method: "GET", path: "/api/Tasks/assignee/{userId}", description: "Tasks per assignee" },
    { method: "GET", path: "/api/Tasks/project/{projectId}", description: "Tasks per project" },
    { method: "POST", path: "/api/Tasks/bulk/assign", description: "Bulk reassign" },
    { method: "POST", path: "/api/Tasks/bulk/move", description: "Bulk move column" },
    { method: "POST", path: "/api/Tasks/bulk/status", description: "Bulk status change" },
    { method: "GET/POST/PUT/DELETE", path: "/api/TaskComments", description: "Task comments" },
    { method: "GET/POST/DELETE", path: "/api/TaskAttachments", description: "Task file attachments" },
    { method: "GET/POST/PUT/DELETE", path: "/api/taskchecklists", description: "Checklists per task" },
    { method: "GET/POST/PUT/DELETE", path: "/api/TaskTimeEntries", description: "Time tracking per task" },
    { method: "POST", path: "/api/TaskTimeEntries/timer/start", description: "Start timer" },
    { method: "GET", path: "/api/TaskTimeEntries/timer/active", description: "Active timer" },
    { method: "POST", path: "/api/TaskTimeEntries/approve/bulk", description: "Approve time entries" },
    { method: "GET/POST/PUT/DELETE", path: "/api/recurringtasks", description: "Recurring task templates" },
    { method: "POST", path: "/api/recurringtasks/generate", description: "Generate occurrences" },
    { method: "GET/POST/PUT/DELETE", path: "/api/ProjectColumns", description: "Kanban columns" },
  ],
  calendar: [
    { method: "GET", path: "/api/Calendar/events", description: "List events in range" },
    { method: "POST", path: "/api/Calendar/events", description: "Create event" },
    { method: "PUT", path: "/api/Calendar/events/{id}", description: "Update event" },
    { method: "DELETE", path: "/api/Calendar/events/{id}", description: "Delete event" },
    { method: "GET", path: "/api/Calendar/event-types", description: "Event type catalog" },
  ],
  "email-calendar": [
    { method: "GET/POST/PUT/DELETE", path: "/api/email-accounts", description: "Connected mailboxes (IMAP/Gmail/Outlook)" },
    { method: "GET", path: "/api/Auth/oauth-config/{provider}", description: "OAuth provider config" },
    { method: "GET/POST/PUT/DELETE", path: "/api/Calendar/events", description: "Synced calendar events" },
  ],
  projects: [
    { method: "GET", path: "/api/Projects", description: "List projects" },
    { method: "GET", path: "/api/Projects/{id}", description: "Project detail" },
    { method: "POST", path: "/api/Projects", description: "Create project" },
    { method: "PUT", path: "/api/Projects/{id}", description: "Update project" },
    { method: "DELETE", path: "/api/Projects/{id}", description: "Delete project" },
    { method: "GET", path: "/api/Projects/search", description: "Full-text search" },
    { method: "GET", path: "/api/Projects/statistics", description: "Project KPIs" },
    { method: "POST", path: "/api/Projects/bulk/archive", description: "Bulk archive" },
    { method: "POST", path: "/api/Projects/bulk/status", description: "Bulk status update" },
    { method: "GET", path: "/api/Projects/contact/{contactId}", description: "Projects per contact" },
    { method: "GET", path: "/api/Projects/owner/{userId}", description: "Projects per owner" },
    { method: "POST/DELETE", path: "/api/Projects/team-member/{projectId}", description: "Manage project team" },
    { method: "GET/POST/PUT/DELETE", path: "/api/Projects/notes/{projectId}", description: "Project notes" },
    { method: "GET/PUT", path: "/api/Projects/settings", description: "Module-level settings" },
  ],
  communication: [
    { method: "GET/POST", path: "/api/AiChat/conversations", description: "AI chat conversations" },
    { method: "GET/POST/DELETE", path: "/api/AiChat/messages", description: "AI chat messages" },
    { method: "POST", path: "/api/AiChat/messages/bulk", description: "Bulk message operations" },
    { method: "POST", path: "/api/GenerateWish", description: "AI text generation" },
    { method: "POST", path: "/api/GenerateWish/stream", description: "Streaming AI generation" },
    { method: "GET/POST/PUT/DELETE", path: "/api/SupportTickets", description: "Internal support tickets" },
  ],
  documents: [
    { method: "GET", path: "/api/Documents", description: "List documents" },
    { method: "GET", path: "/api/Documents/{id}", description: "Document metadata" },
    { method: "POST", path: "/api/Documents/upload", description: "Upload file(s)" },
    { method: "GET", path: "/api/Documents/download/{id}", description: "Download file" },
    { method: "POST", path: "/api/Documents/bulk-delete", description: "Bulk delete" },
    { method: "GET", path: "/api/Documents/stats", description: "Storage stats" },
    { method: "GET/POST/PUT/DELETE", path: "/api/EntityFormDocuments", description: "Documents bound to forms" },
    { method: "POST", path: "/api/EntityFormDocuments/copy", description: "Copy attachments across entities" },
    { method: "POST", path: "/api/Upload/file", description: "Generic single file upload" },
    { method: "POST", path: "/api/Upload/files", description: "Generic multi-file upload" },
  ],
  workflow: [
    { method: "GET/POST/PUT/DELETE", path: "/api/workflows", description: "Workflow definitions" },
    { method: "GET", path: "/api/workflows/default", description: "Default workflows" },
    { method: "GET", path: "/api/workflow-executions", description: "Execution history" },
    { method: "POST", path: "/api/workflow-executions/trigger-manual", description: "Manually trigger run" },
    { method: "POST", path: "/api/workflow-executions/cleanup-stuck", description: "Recover stuck runs" },
    { method: "GET/POST/PUT", path: "/api/workflow-approvals", description: "Approval steps" },
    { method: "GET", path: "/api/workflow-reconciliation/status", description: "Reconciliation health" },
    { method: "POST", path: "/api/workflow-reconciliation/run", description: "Run reconciliation" },
  ],
  automation: [
    { method: "GET/POST/PUT/DELETE", path: "/api/workflows", description: "Automation rules (workflow engine)" },
    { method: "POST", path: "/api/workflow-executions/trigger-manual", description: "Trigger automation" },
    { method: "GET/POST/PUT/DELETE", path: "/api/recurringtasks", description: "Scheduled recurring jobs" },
  ],
  external: [
    { method: "GET/POST/PUT/DELETE", path: "/api/external-endpoints", description: "Public webhook/API endpoints" },
    { method: "GET", path: "/api/external-endpoints/stats", description: "Hit counters" },
    { method: "POST", path: "/api/external-receive/{slug}", description: "Public ingestion endpoint (e.g. contact form)" },
    { method: "POST", path: "/api/ExternalApiProxy/fetch", description: "Server-side outbound HTTP proxy" },
    { method: "POST", path: "/api/uploadthing/prepare", description: "Signed-upload prepare" },
    { method: "DELETE", path: "/api/uploadthing/delete", description: "Signed-upload delete" },
  ],
  analytics: [
    { method: "GET", path: "/api/reports", description: "Available reports" },
    { method: "GET", path: "/api/reports/sales", description: "Sales analytics" },
    { method: "GET", path: "/api/reports/service-orders", description: "Service-order analytics" },
    { method: "GET", path: "/api/reports/technicians", description: "Technician productivity" },
    { method: "GET", path: "/api/reports/export/{report}", description: "Export to CSV/PDF" },
    { method: "GET", path: "/api/SystemLogs/statistics", description: "System activity stats" },
  ],
  "website-builder": [
    { method: "GET/POST/PUT/DELETE", path: "/api/WBSites", description: "Sites" },
    { method: "GET", path: "/api/WBSites/slug/{slug}", description: "Resolve site by slug" },
    { method: "GET/POST/PUT/DELETE", path: "/api/WBPages", description: "Pages per site" },
    { method: "POST", path: "/api/WBPages/reorder", description: "Reorder pages" },
    { method: "GET/POST/PUT/DELETE", path: "/api/WBGlobalBlocks", description: "Reusable blocks (header/footer)" },
    { method: "GET/POST/PUT/DELETE", path: "/api/WBBrandProfiles", description: "Brand profile (colors/fonts/logo)" },
    { method: "GET/POST", path: "/api/WBMedia", description: "Media library" },
    { method: "POST", path: "/api/WBUpload/file", description: "Upload media" },
    { method: "GET", path: "/api/WBTemplates", description: "Templates" },
    { method: "GET", path: "/api/WBTemplates/categories", description: "Template categories" },
    { method: "GET/POST", path: "/api/WBFormSubmissions", description: "Form submissions" },
    { method: "GET", path: "/api/WBActivityLog/site/{siteId}", description: "Edit / publish history" },
    { method: "POST", path: "/api/public/sites/{slug}", description: "Public site rendering" },
    { method: "POST", path: "/api/public/forms", description: "Public form ingestion" },
  ],
  lookups: [
    { method: "GET", path: "/api/Lookups/{type}", description: "Generic lookup list (units, statuses, …)" },
    { method: "POST", path: "/api/Lookups/{type}", description: "Create lookup value" },
    { method: "PUT", path: "/api/Lookups/{type}/{id}", description: "Update value" },
    { method: "DELETE", path: "/api/Lookups/{type}/{id}", description: "Delete value" },
    { method: "GET", path: "/api/Lookups/currencies", description: "Currencies list" },
    { method: "GET/POST/PUT/DELETE", path: "/api/articles/categories", description: "Article categories" },
    { method: "GET/POST/PUT/DELETE", path: "/api/articles/groups", description: "Article groups" },
  ],
  notifications: [
    { method: "GET", path: "/api/Notifications", description: "List notifications" },
    { method: "GET", path: "/api/Notifications/unread-count", description: "Unread badge count" },
    { method: "POST", path: "/api/Notifications/read", description: "Mark notifications as read" },
    { method: "POST", path: "/api/Notifications/read-all", description: "Mark all as read" },
    { method: "DELETE", path: "/api/Notifications/{id}", description: "Delete notification" },
  ],
  settings: [
    { method: "GET/PUT", path: "/api/settings/app", description: "Application settings" },
    { method: "GET/PUT", path: "/api/settings/numbering", description: "Document numbering schemes" },
    { method: "POST", path: "/api/settings/numbering/validate", description: "Validate numbering pattern" },
    { method: "GET/PUT", path: "/api/settings/working-hours", description: "Working hours" },
    { method: "GET/PUT", path: "/api/settings/planner", description: "Planner preferences" },
    { method: "GET/PUT", path: "/api/PdfSettings", description: "PDF templates / branding" },
    { method: "GET/PUT", path: "/api/Preferences", description: "Per-user preferences" },
    { method: "GET", path: "/api/Tenants", description: "Tenant info" },
    { method: "GET/POST/PUT/DELETE", path: "/api/Users", description: "Users management" },
    { method: "GET", path: "/api/Users/check-email", description: "Email availability" },
    { method: "GET/POST/PUT/DELETE", path: "/api/Roles", description: "Roles" },
    { method: "GET", path: "/api/Roles/all-user-roles", description: "Role assignments overview" },
    { method: "GET/PUT", path: "/api/Permissions/role/{roleId}", description: "Role permissions" },
    { method: "GET", path: "/api/Permissions/user/{userId}", description: "Effective user permissions" },
    { method: "GET/POST/PUT/DELETE", path: "/api/Skills", description: "Skill catalog" },
    { method: "GET/POST/PUT/DELETE", path: "/api/UserAiSettings/keys", description: "User AI provider keys" },
    { method: "GET/PUT", path: "/api/UserAiSettings/preferences", description: "AI preferences" },
    { method: "GET/POST/PUT/DELETE", path: "/api/plugins", description: "Plugins/modules toggles" },
    { method: "GET", path: "/api/plugins/stats", description: "Plugin usage stats" },
    { method: "GET/POST", path: "/api/Signatures/me", description: "User signature" },
    { method: "GET/POST/PUT", path: "/api/OfflineHydrationPreferences", description: "Offline-mode prefetch rules" },
    { method: "GET/POST", path: "/api/sync/pull", description: "Offline sync pull" },
    { method: "POST", path: "/api/sync/push", description: "Offline sync push" },
    { method: "GET", path: "/api/sync/history", description: "Sync history" },
    { method: "POST", path: "/api/sync/retry", description: "Retry failed sync" },
    { method: "GET", path: "/api/SystemLogs", description: "System logs" },
    { method: "GET", path: "/api/SystemLogs/export", description: "Export logs" },
    { method: "POST", path: "/api/SystemLogs/cleanup", description: "Purge logs" },
    { method: "GET", path: "/api/subscriptions", description: "Billing subscription info" },
    { method: "GET", path: "/api/version", description: "Server version" },
  ],
};

// Backend entities — these are the relational tables/collections that back
// each module on the server side (.NET / EF Core naming).
export const MODULE_TABLES: Record<string, string[]> = {
  dashboard: ["Dashboards", "DashboardWidgets", "DashboardShares", "SystemLogs"],
  contacts: ["Contacts", "ContactNotes", "ContactTags", "ContactTagLinks", "ContactAddresses", "ContactCustomFields"],
  offers: ["Offers", "OfferItems", "OfferStatuses", "OfferAttachments", "OfferRevisions"],
  sales: ["Sales", "SaleItems", "SalePayments", "SaleStatuses", "SaleAttachments"],
  deals: ["Offers", "Sales", "DealStages", "DealActivities"],
  articles: ["Articles", "ArticleCategories", "ArticleGroups", "ArticleNotes", "ArticleSuppliers", "ArticleAttachments"],
  "inventory-services": ["Articles (type=Service)", "ServiceUnits", "ServiceRates"],
  "stock-management": ["StockTransactions", "StockLocations", "ArticleStockLevels", "StockAdjustments", "StockTransfers"],
  purchases: ["PurchaseOrders", "PurchaseOrderItems", "GoodsReceipts", "GoodsReceiptItems", "SupplierInvoices", "SupplierInvoiceItems", "ArticleSuppliers"],
  hr: [
    "Employees", "Departments", "Contracts", "Attendance", "AttendanceSettings",
    "Leaves", "LeaveBalances", "LeaveTypes", "PayrollRuns", "Payslips", "PayslipLines",
    "Bonuses", "Holidays", "CnssRates", "CnssDeclarations",
    "PerformanceCycles", "PerformanceGoals", "PerformanceReviews",
    "JobOpenings", "Applicants", "Interviews", "InterviewNotes",
    "HrDocuments", "HrAuditLog",
  ],
  field: ["Dispatches", "DispatchItems", "Installations", "InstallationNotes", "ServiceOrders", "ServiceOrderItems", "ServiceOrderJobPaths", "TechnicianAssignments"],
  scheduling: ["Schedules", "ScheduleEntries", "Leaves", "WorkingHours", "PlannerSettings"],
  tasks: [
    "Tasks (project)", "Tasks (daily)", "TaskColumns", "ProjectColumns",
    "TaskComments", "TaskAttachments", "TaskChecklists", "TaskChecklistItems",
    "TaskTimeEntries", "RecurringTasks",
  ],
  calendar: ["CalendarEvents", "CalendarEventTypes", "CalendarReminders", "CalendarShares"],
  "email-calendar": ["EmailAccounts", "EmailMessages", "EmailFolders", "OAuthTokens", "CalendarEvents"],
  projects: ["Projects", "ProjectMembers", "ProjectColumns", "ProjectNotes", "ProjectAttachments", "ProjectSettings"],
  communication: ["AiConversations", "AiMessages", "SupportTickets", "SupportTicketMessages"],
  documents: ["Documents", "DocumentVersions", "DocumentFolders", "EntityFormDocuments", "Uploads"],
  workflow: ["Workflows", "WorkflowSteps", "WorkflowExecutions", "WorkflowExecutionSteps", "WorkflowApprovals", "WorkflowReconciliation"],
  automation: ["Workflows", "WorkflowTriggers", "RecurringTasks", "ScheduledJobs"],
  external: ["ExternalEndpoints", "ExternalEndpointHits", "ExternalReceiveLogs", "Webhooks", "ApiKeys"],
  analytics: ["Reports", "ReportRuns", "ReportExports", "SystemLogs", "AnalyticsAggregates"],
  "website-builder": ["WBSites", "WBPages", "WBGlobalBlocks", "WBBrandProfiles", "WBMedia", "WBTemplates", "WBFormSubmissions", "WBActivityLog"],
  lookups: ["Lookups", "Currencies", "ArticleCategories", "ArticleGroups", "Units", "TaxRates"],
  notifications: ["Notifications", "NotificationTypes", "NotificationSubscriptions"],
  settings: [
    "AppSettings", "PdfSettings", "Preferences", "WorkingHours", "PlannerSettings",
    "NumberingSchemes", "Tenants", "Users", "Roles", "Permissions", "RolePermissions",
    "UserRoles", "Skills", "UserSkills", "UserAiSettings", "AiProviderKeys",
    "Plugins", "Signatures", "OfflineHydrationPreferences", "SyncHistory",
    "SystemLogs", "Subscriptions",
  ],
};
