import { PaletteItem } from '../../types';

export const ADVANCED_PALETTE: PaletteItem[] = [
  {
    type: 'custom-html', label: 'Custom HTML', icon: 'Code2', category: 'advanced',
    description: 'Raw HTML/CSS/JS embed',
    defaultProps: { html: '<div style="padding: 20px; text-align: center;">\n  <h3>Custom HTML Block</h3>\n  <p>Add any HTML here</p>\n</div>' },
  },
  {
    type: 'cookie-consent', label: 'Cookie Consent', icon: 'Cookie', category: 'advanced',
    description: 'GDPR cookie banner',
    defaultProps: { text: 'We use cookies to enhance your browsing experience and analyze site traffic.', buttonText: 'Accept All', learnMoreText: 'Privacy Policy', learnMoreUrl: '#', position: 'bottom' },
  },
  {
    type: 'whatsapp-button', label: 'WhatsApp Button', icon: 'MessageCircle', category: 'advanced',
    description: 'Floating chat button with greeting',
    defaultProps: {
      phoneNumber: '+1234567890',
      defaultMessage: 'Hello! I have a question.',
      displayMode: 'floating',
      position: 'bottom-right',
      stickyPosition: 'bottom',
      buttonColor: '#25D366',
      iconColor: '#ffffff',
      iconSize: 56,
      pulseAnimation: true,
      showGreeting: true,
      greetingText: 'Hi there! 👋 How can we help you today?',
      greetingDelay: 3,
      avatarUrl: '',
      agentName: 'Support',
      businessHoursEnabled: false,
      businessHoursStart: '09:00',
      businessHoursEnd: '18:00',
      businessDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
      offlineMessage: "We're currently offline. Leave us a message!",
      tooltipText: 'Chat with us',
      stickyText: 'Chat with us on WhatsApp',
      offsetX: 24,
      offsetY: 24,
    },
  },
  {
    type: 'facebook-pixel', label: 'Meta Pixel', icon: 'Activity', category: 'advanced',
    description: 'Facebook/Meta tracking pixel',
    defaultProps: {
      pixelId: '',
      enablePageView: true,
      enablePurchase: false,
      enableLead: true,
      enableAddToCart: false,
      customEvents: [],
    },
  },
  {
    type: 'google-analytics', label: 'Google Analytics', icon: 'BarChart3', category: 'advanced',
    description: 'GA4/Ads tracking & conversions',
    defaultProps: {
      measurementId: '',
      enablePageView: true,
      enableConversions: false,
      conversionLabel: '',
      conversionValue: '',
      enableRemarketing: false,
      customDimensions: [],
    },
  },
  {
    type: 'loading-screen', label: 'Loading Screen', icon: 'Timer', category: 'advanced',
    description: 'Animated preloader',
    defaultProps: {
      variant: 'spinner',
      logoText: '',
      logoImage: '',
      backgroundColor: '#ffffff',
      accentColor: '#3B82F6',
      textColor: '#333333',
      loadingText: 'Loading...',
      showPercentage: false,
      duration: 3,
    },
  },
  {
    type: 'floating-cta', label: 'Floating CTA', icon: 'Megaphone', category: 'advanced',
    description: 'Sticky call-to-action button',
    defaultProps: {
      text: 'Get Started Now',
      link: '#',
      icon: 'ArrowRight',
      position: 'bottom-center',
      backgroundColor: '',
      textColorOverride: '#ffffff',
      showAfterScroll: 200,
      animation: 'slide-up',
      dismissible: true,
      pill: true,
      offsetX: 24,
      offsetY: 24,
    },
  },
  {
    type: 'scroll-to-top', label: 'Scroll to Top', icon: 'ArrowUpCircle', category: 'advanced',
    description: 'Floating back-to-top button',
    defaultProps: {
      icon: 'ArrowUp',
      displayMode: 'floating',
      position: 'bottom-right',
      backgroundColor: '',
      iconColor: '#ffffff',
      size: 44,
      showAfterScroll: 300,
      smooth: true,
      rounded: true,
      shadow: true,
      offsetX: 24,
      offsetY: 24,
      animation: 'fade',
    },
  },
];
