-- =============================================================================
-- Migration: Direct Service Orders (no Offer / Sale parent)
-- =============================================================================
-- Adds:
--   ServiceOrders.Origin                  : 'from_offer' | 'from_sale' | 'direct'
--   ServiceOrders.AutoGeneratedSaleId     : FK back to the shadow Sale generated
--                                            on completion of a direct order
--   Sales.IsAutoGenerated                 : true when the Sale was created
--                                            automatically by completing a direct
--                                            ServiceOrder
--   Sales.SourceServiceOrderId            : FK back to the ServiceOrder that
--                                            generated this Sale
--
-- ServiceOrders.SaleId / OfferId are already nullable text columns — no change
-- needed there.
--
-- Backfill rule: every existing ServiceOrder is assumed to come from a Sale
-- (today's only path), so default Origin = 'from_sale'. Direct creation will
-- stamp 'direct' going forward.
-- =============================================================================

BEGIN;

-- ServiceOrders ---------------------------------------------------------------
ALTER TABLE "ServiceOrders"
    ADD COLUMN IF NOT EXISTS "Origin" varchar(20) NOT NULL DEFAULT 'from_sale',
    ADD COLUMN IF NOT EXISTS "AutoGeneratedSaleId" int NULL;

-- Backfill: any row that has no SaleId AND no OfferId AND was created before
-- this migration is still tagged 'from_sale' (safe default). New rows created
-- through POST /api/service-orders/direct will explicitly set 'direct'.
UPDATE "ServiceOrders"
SET "Origin" = 'from_sale'
WHERE "Origin" IS NULL OR "Origin" = '';

CREATE INDEX IF NOT EXISTS "ix_ServiceOrders_Origin"
    ON "ServiceOrders" ("Origin");

CREATE INDEX IF NOT EXISTS "ix_ServiceOrders_AutoGeneratedSaleId"
    ON "ServiceOrders" ("AutoGeneratedSaleId")
    WHERE "AutoGeneratedSaleId" IS NOT NULL;

-- Sales -----------------------------------------------------------------------
ALTER TABLE "Sales"
    ADD COLUMN IF NOT EXISTS "IsAutoGenerated" boolean NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS "SourceServiceOrderId" int NULL;

CREATE INDEX IF NOT EXISTS "ix_Sales_SourceServiceOrderId"
    ON "Sales" ("SourceServiceOrderId")
    WHERE "SourceServiceOrderId" IS NOT NULL;

CREATE INDEX IF NOT EXISTS "ix_Sales_IsAutoGenerated"
    ON "Sales" ("IsAutoGenerated")
    WHERE "IsAutoGenerated" = true;

-- Soft FKs (no hard constraint to avoid cross-module coupling at the DB layer;
-- application enforces integrity through the ShadowSaleGenerator transaction).

COMMIT;
