import type { WidgetRegistryEntry, WidgetType } from '../types';

const ALL_DATA_SOURCES = [
  'sales', 'offers', 'contacts', 'tasks', 'articles',
  'serviceOrders', 'dispatches', 'timeExpenses', 'externalApi',
] as const;

export const WIDGET_REGISTRY: Record<WidgetType, WidgetRegistryEntry> = {
  kpi: {
    type: 'kpi',
    labelKey: 'dashboardBuilder.widgets.kpi',
    icon: 'Hash',
    defaultLayout: { x: 0, y: 0, w: 3, h: 2, minW: 2, minH: 2, maxH: 3 },
    supportedMetrics: ['count', 'total', 'revenue', 'average', 'conversionRate', 'completionRate'],
    supportedDataSources: [...ALL_DATA_SOURCES],
    category: 'kpi',
  },
  bar: {
    type: 'bar',
    labelKey: 'dashboardBuilder.widgets.bar',
    icon: 'BarChart3',
    defaultLayout: { x: 0, y: 0, w: 6, h: 4, minW: 3, minH: 3 },
    supportedMetrics: ['statusBreakdown', 'priorityBreakdown', 'monthlyTrend', 'topItems'],
    supportedDataSources: [...ALL_DATA_SOURCES],
    category: 'chart',
  },
  pie: {
    type: 'pie',
    labelKey: 'dashboardBuilder.widgets.pie',
    icon: 'PieChart',
    defaultLayout: { x: 0, y: 0, w: 4, h: 4, minW: 3, minH: 3 },
    supportedMetrics: ['statusBreakdown', 'priorityBreakdown'],
    supportedDataSources: [...ALL_DATA_SOURCES],
    category: 'chart',
  },
  donut: {
    type: 'donut',
    labelKey: 'dashboardBuilder.widgets.donut',
    icon: 'CircleDot',
    defaultLayout: { x: 0, y: 0, w: 4, h: 4, minW: 3, minH: 3 },
    supportedMetrics: ['statusBreakdown', 'priorityBreakdown'],
    supportedDataSources: [...ALL_DATA_SOURCES],
    category: 'chart',
  },
  line: {
    type: 'line',
    labelKey: 'dashboardBuilder.widgets.line',
    icon: 'TrendingUp',
    defaultLayout: { x: 0, y: 0, w: 6, h: 4, minW: 3, minH: 3 },
    supportedMetrics: ['monthlyTrend', 'revenue'],
    supportedDataSources: [...ALL_DATA_SOURCES],
    category: 'chart',
  },
  area: {
    type: 'area',
    labelKey: 'dashboardBuilder.widgets.area',
    icon: 'AreaChart',
    defaultLayout: { x: 0, y: 0, w: 6, h: 4, minW: 3, minH: 3 },
    supportedMetrics: ['monthlyTrend', 'revenue'],
    supportedDataSources: [...ALL_DATA_SOURCES],
    category: 'chart',
  },
  table: {
    type: 'table',
    labelKey: 'dashboardBuilder.widgets.table',
    icon: 'Table',
    defaultLayout: { x: 0, y: 0, w: 6, h: 5, minW: 4, minH: 3 },
    supportedMetrics: ['topItems'],
    supportedDataSources: [...ALL_DATA_SOURCES],
    category: 'data',
  },
  gauge: {
    type: 'gauge',
    labelKey: 'dashboardBuilder.widgets.gauge',
    icon: 'Gauge',
    defaultLayout: { x: 0, y: 0, w: 3, h: 3, minW: 2, minH: 2 },
    supportedMetrics: ['conversionRate', 'completionRate'],
    supportedDataSources: [...ALL_DATA_SOURCES],
    category: 'progress',
  },
  sparkline: {
    type: 'sparkline',
    labelKey: 'dashboardBuilder.widgets.sparkline',
    icon: 'Activity',
    defaultLayout: { x: 0, y: 0, w: 3, h: 2, minW: 2, minH: 2 },
    supportedMetrics: ['monthlyTrend'],
    supportedDataSources: [...ALL_DATA_SOURCES],
    category: 'kpi',
  },
  funnel: {
    type: 'funnel',
    labelKey: 'dashboardBuilder.widgets.funnel',
    icon: 'Filter',
    defaultLayout: { x: 0, y: 0, w: 4, h: 4, minW: 3, minH: 3 },
    supportedMetrics: ['statusBreakdown'],
    supportedDataSources: ['sales', 'offers', 'serviceOrders'],
    category: 'chart',
  },
  radar: {
    type: 'radar',
    labelKey: 'dashboardBuilder.widgets.radar',
    icon: 'Radar',
    defaultLayout: { x: 0, y: 0, w: 5, h: 4, minW: 3, minH: 3 },
    supportedMetrics: ['statusBreakdown', 'priorityBreakdown'],
    supportedDataSources: [...ALL_DATA_SOURCES],
    category: 'chart',
  },
  stackedBar: {
    type: 'stackedBar',
    labelKey: 'dashboardBuilder.widgets.stackedBar',
    icon: 'BarChart3',
    defaultLayout: { x: 0, y: 0, w: 6, h: 4, minW: 3, minH: 3 },
    supportedMetrics: ['statusBreakdown', 'priorityBreakdown'],
    supportedDataSources: [...ALL_DATA_SOURCES],
    category: 'chart',
  },
  heatmap: {
    type: 'heatmap',
    labelKey: 'dashboardBuilder.widgets.heatmap',
    icon: 'Grid3x3',
    defaultLayout: { x: 0, y: 0, w: 6, h: 3, minW: 3, minH: 2 },
    supportedMetrics: ['statusBreakdown', 'priorityBreakdown', 'monthlyTrend'],
    supportedDataSources: [...ALL_DATA_SOURCES],
    category: 'chart',
  },
  map: {
    type: 'map',
    labelKey: 'dashboardBuilder.widgets.map',
    icon: 'MapPin',
    defaultLayout: { x: 0, y: 0, w: 6, h: 4, minW: 3, minH: 3 },
    supportedMetrics: ['count', 'statusBreakdown'],
    supportedDataSources: ['contacts', 'dispatches', 'serviceOrders', 'tasks', 'sales'],
    category: 'data',
  },
};

export const getWidgetsByCategory = () => {
  const entries = Object.values(WIDGET_REGISTRY);
  return {
    kpi: entries.filter(e => e.category === 'kpi'),
    chart: entries.filter(e => e.category === 'chart'),
    data: entries.filter(e => e.category === 'data'),
    progress: entries.filter(e => e.category === 'progress'),
  };
};
