
import * as Lucide from 'lucide-react';

// Build a large registry from commonly used lucide icons.
export const ICON_REGISTRY = {
  Home: Lucide.Home,
  Users: Lucide.Users,
  TrendingUp: Lucide.TrendingUp,
  Package: Lucide.Package,
  CheckSquare: Lucide.CheckSquare,
  Calendar: Lucide.Calendar,
  CalendarDays: Lucide.CalendarDays,
  Wrench: Lucide.Wrench,
  CalendarRange: Lucide.CalendarRange,
  Boxes: Lucide.Boxes,
  Database: Lucide.Database,
  Settings: Lucide.Settings,
  Building: Lucide.Building,
  BarChart3: Lucide.BarChart3,
  ClipboardList: Lucide.ClipboardList,
  Clock: Lucide.Clock,
  Bell: Lucide.Bell,
  CalendarCheck: Lucide.CalendarCheck,
  CreditCard: Lucide.CreditCard,
  FileText: Lucide.FileText,
  Globe: Lucide.Globe,
  Layers: Lucide.Layers,
  MapPin: Lucide.MapPin,
  MessageCircle: Lucide.MessageCircle,
  Phone: Lucide.Phone,
  Star: Lucide.Star,
  Tag: Lucide.Tag,
  Tool: Lucide.Settings,
  UserCheck: Lucide.UserCheck,
  Activity: Lucide.Activity,
  Archive: Lucide.Archive,
  AtSign: Lucide.AtSign,
  BookOpen: Lucide.BookOpen,
  Briefcase: Lucide.Briefcase,
  Code: Lucide.Code,
  Compass: Lucide.Compass,
  Cpu: Lucide.Cpu,
  DollarSign: Lucide.DollarSign,
  DownloadCloud: Lucide.DownloadCloud,
  Edit: Lucide.Edit,
  Eye: Lucide.Eye,
  File: Lucide.File,
  Flag: Lucide.Flag,
  Folder: Lucide.Folder,
  Gift: Lucide.Gift,
  Heart: Lucide.Heart,
  Image: Lucide.Image,
  Key: Lucide.Key,
  Link: Lucide.Link,
  List: Lucide.List,
  Lock: Lucide.Lock,
  Mail: Lucide.Mail,
  Monitor: Lucide.Monitor,
  Music: Lucide.Music,
  Paperclip: Lucide.Paperclip,
  PieChart: Lucide.PieChart,
  Printer: Lucide.Printer,
  RefreshCcw: Lucide.RefreshCcw,
  Search: Lucide.Search,
  Share2: Lucide.Share2,
  ShieldCheck: Lucide.ShieldCheck,
  ShoppingCart: Lucide.ShoppingCart,
  Sun: Lucide.Sun,
  ThumbsUp: Lucide.ThumbsUp,
  Trash: Lucide.Trash,
  Truck: Lucide.Truck,
  Unlock: Lucide.Unlock,
  Video: Lucide.Video,
  Zap: Lucide.Zap,
  Workflow: Lucide.Workflow,
  UserCog: Lucide.UserCog,
  GitBranch: Lucide.GitBranch,
} as const;

export const ICON_OPTIONS = Object.keys(ICON_REGISTRY) as Array<keyof typeof ICON_REGISTRY>;

export type IconName = keyof typeof ICON_REGISTRY;
